package custom.lease.model.View;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 19 19:14:29 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxplBookingCustomer_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XxplBookingCustomer_VOImpl() {
    }
}
