package custom.lease.model.View;

import custom.lease.model.Entity.XxplCancellationCharge_EOImpl;

import java.math.BigDecimal;

import java.sql.Date;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 02 14:43:00 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxplCancellationCharge_VORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Amount {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getAmount();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setAmount((BigDecimal)value);
            }
        }
        ,
        Attribute1 {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        AttributeCategory {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getAttributeCategory();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setAttributeCategory((String)value);
            }
        }
        ,
        CancelChargeId {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getCancelChargeId();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setCancelChargeId((Number)value);
            }
        }
        ,
        CancelId {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getCancelId();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setCancelId((BigDecimal)value);
            }
        }
        ,
        ChargeName {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getChargeName();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setChargeName((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setCreationDate((Timestamp)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setLastUpdateDate((Timestamp)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setLastUpdateLogin((String)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        ObjectVersionNumber {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getObjectVersionNumber();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setObjectVersionNumber((BigDecimal)value);
            }
        }
        ,
        TaxCode {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getTaxCode();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setTaxCode((String)value);
            }
        }
        ,
        TaxRate {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getTaxRate();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setTaxRate((BigDecimal)value);
            }
        }
        ,
        TotalAmount {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getTotalAmount();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setTotalAmount((BigDecimal)value);
            }
        }
        ,
        VatAmount {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getVatAmount();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setVatAmount((BigDecimal)value);
            }
        }
        ,
        InterfaceStatus {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getInterfaceStatus();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setInterfaceStatus((String)value);
            }
        }
        ,
        InvoiceNumber {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getInvoiceNumber();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setInvoiceNumber((String)value);
            }
        }
        ,
        ErrorMsg {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getErrorMsg();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setErrorMsg((String)value);
            }
        }
        ,
        CustomerTrxId {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getCustomerTrxId();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setCustomerTrxId((BigDecimal)value);
            }
        }
        ,
        CancelCharType {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getCancelCharType();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setCancelCharType((String)value);
            }
        }
        ,
        CanAmtApply {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getCanAmtApply();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setCanAmtApply((BigDecimal)value);
            }
        }
        ,
        CanFlag {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getCanFlag();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setCanFlag((String)value);
            }
        }
        ,
        CanGlDate {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getCanGlDate();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setCanGlDate((Date)value);
            }
        }
        ,
        CancellatinCharge_LOOKUP {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getCancellatinCharge_LOOKUP();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Tax_LOOKUP {
            public Object get(XxplCancellationCharge_VORowImpl obj) {
                return obj.getTax_LOOKUP();
            }

            public void put(XxplCancellationCharge_VORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(XxplCancellationCharge_VORowImpl object);

        public abstract void put(XxplCancellationCharge_VORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTECATEGORY = AttributesEnum.AttributeCategory.index();
    public static final int CANCELCHARGEID = AttributesEnum.CancelChargeId.index();
    public static final int CANCELID = AttributesEnum.CancelId.index();
    public static final int CHARGENAME = AttributesEnum.ChargeName.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int OBJECTVERSIONNUMBER = AttributesEnum.ObjectVersionNumber.index();
    public static final int TAXCODE = AttributesEnum.TaxCode.index();
    public static final int TAXRATE = AttributesEnum.TaxRate.index();
    public static final int TOTALAMOUNT = AttributesEnum.TotalAmount.index();
    public static final int VATAMOUNT = AttributesEnum.VatAmount.index();
    public static final int INTERFACESTATUS = AttributesEnum.InterfaceStatus.index();
    public static final int INVOICENUMBER = AttributesEnum.InvoiceNumber.index();
    public static final int ERRORMSG = AttributesEnum.ErrorMsg.index();
    public static final int CUSTOMERTRXID = AttributesEnum.CustomerTrxId.index();
    public static final int CANCELCHARTYPE = AttributesEnum.CancelCharType.index();
    public static final int CANAMTAPPLY = AttributesEnum.CanAmtApply.index();
    public static final int CANFLAG = AttributesEnum.CanFlag.index();
    public static final int CANGLDATE = AttributesEnum.CanGlDate.index();
    public static final int CANCELLATINCHARGE_LOOKUP = AttributesEnum.CancellatinCharge_LOOKUP.index();
    public static final int TAX_LOOKUP = AttributesEnum.Tax_LOOKUP.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxplCancellationCharge_VORowImpl() {
    }

    /**
     * Gets XxplCancellationCharge_EO entity object.
     * @return the XxplCancellationCharge_EO
     */
    public XxplCancellationCharge_EOImpl getXxplCancellationCharge_EO() {
        return (XxplCancellationCharge_EOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for AMOUNT using the alias name Amount.
     * @return the AMOUNT
     */
    public BigDecimal getAmount() {
        String chargeName = this.getChargeName();
        BigDecimal chargeAmt = new BigDecimal(0); 
        BigDecimal vatAmt = new BigDecimal(0);
        BigDecimal totalAmt = new BigDecimal(0);
        BigDecimal taxRate = new BigDecimal(0);
//        ----------------------------
//        if(
//        "RENT_INCOME_DAY_CONSUM".equals(chargeName) || 
//        "TWO_MONTH_PENALTY".equals(chargeName) || 
//        "CHEQUE_WITHDRA_FEE".equals(chargeName)||
//        "ACCESS_CARD".equals(chargeName)
//        ){
//            chargeAmt = this.getAmount()!=null?this.getAmount():new BigDecimal(0);
//            vatAmt = this.getVatAmount()!=null?this.getVatAmount():new BigDecimal(0);
//            totalAmt = chargeAmt.add(vatAmt);
//            this.setTotalAmount(totalAmt);
//        } 
        
        if("TOTAL".equals(chargeName)){
            XxplCancellationCharge_VOImpl impl = (XxplCancellationCharge_VOImpl)getViewObject();
            chargeAmt = impl.getChargeSumAmt();
            System.err.println("chargeAmt"+chargeAmt);
            return chargeAmt;
        }
        return (BigDecimal) getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for AMOUNT using the alias name Amount.
     * @param value value to set the AMOUNT
     */
    public void setAmount(BigDecimal value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @return the ATTRIBUTE_CATEGORY
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @param value value to set the ATTRIBUTE_CATEGORY
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for CANCEL_CHARGE_ID using the alias name CancelChargeId.
     * @return the CANCEL_CHARGE_ID
     */
    public Number getCancelChargeId() {
        return (Number)getAttributeInternal(CANCELCHARGEID);
    }

    /**
     * Sets <code>value</code> as attribute value for CANCEL_CHARGE_ID using the alias name CancelChargeId.
     * @param value value to set the CANCEL_CHARGE_ID
     */
    public void setCancelChargeId(Number value) {
        setAttributeInternal(CANCELCHARGEID, value);
    }

    /**
     * Gets the attribute value for CANCEL_ID using the alias name CancelId.
     * @return the CANCEL_ID
     */
    public BigDecimal getCancelId() {
        return (BigDecimal) getAttributeInternal(CANCELID);
    }

    /**
     * Sets <code>value</code> as attribute value for CANCEL_ID using the alias name CancelId.
     * @param value value to set the CANCEL_ID
     */
    public void setCancelId(BigDecimal value) {
        setAttributeInternal(CANCELID, value);
    }

    /**
     * Gets the attribute value for CHARGE_NAME using the alias name ChargeName.
     * @return the CHARGE_NAME
     */
    public String getChargeName() {
        return (String) getAttributeInternal(CHARGENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CHARGE_NAME using the alias name ChargeName.
     * @param value value to set the CHARGE_NAME
     */
    public void setChargeName(String value) {
        setAttributeInternal(CHARGENAME, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @return the OBJECT_VERSION_NUMBER
     */
    public BigDecimal getObjectVersionNumber() {
        return (BigDecimal) getAttributeInternal(OBJECTVERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @param value value to set the OBJECT_VERSION_NUMBER
     */
    public void setObjectVersionNumber(BigDecimal value) {
        setAttributeInternal(OBJECTVERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for TAX_CODE using the alias name TaxCode.
     * @return the TAX_CODE
     */
    public String getTaxCode() {
        return (String) getAttributeInternal(TAXCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_CODE using the alias name TaxCode.
     * @param value value to set the TAX_CODE
     */
    public void setTaxCode(String value) {
        setAttributeInternal(TAXCODE, value);
    }

    /**
     * Gets the attribute value for TAX_RATE using the alias name TaxRate.
     * @return the TAX_RATE
     */
    public BigDecimal getTaxRate() {
        return (BigDecimal) getAttributeInternal(TAXRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_RATE using the alias name TaxRate.
     * @param value value to set the TAX_RATE
     */
    public void setTaxRate(BigDecimal value) {
        setAttributeInternal(TAXRATE, value);
    }

    /**
     * Gets the attribute value for TOTAL_AMOUNT using the alias name TotalAmount.
     * @return the TOTAL_AMOUNT
     */
    public BigDecimal getTotalAmount() {
        String chargeName = this.getChargeName();
        BigDecimal chargeAmt = new BigDecimal(0);
        BigDecimal vatAmt = new BigDecimal(0);
        BigDecimal totalAmt = new BigDecimal(0);
        
        if(
        "RENT_INCOME_DAY_CONSUM".equals(chargeName) || 
        "TWO_MONTH_PENALTY".equals(chargeName) || 
        "CHEQUE_WITHDRA_FEE".equals(chargeName)||
        "ACCESS_CARD".equals(chargeName)
        ){
            chargeAmt = this.getAmount()!=null?this.getAmount():new BigDecimal(0);
            vatAmt = this.getVatAmount()!=null?this.getVatAmount():new BigDecimal(0);
            totalAmt = chargeAmt.add(vatAmt);
            this.setTotalAmount(totalAmt);
            return totalAmt;
            
        } 
        if("TOTAL".equals(chargeName)){
            XxplCancellationCharge_VOImpl impl = (XxplCancellationCharge_VOImpl)getViewObject();
            totalAmt = impl.getTotalSumAmt();
            this.setTotalAmount(totalAmt);
            return totalAmt;
        } 
        if("DUE_TAB1".equals(chargeName)){
            XxplCancellationCharge_VOImpl impl = (XxplCancellationCharge_VOImpl)getViewObject();
            totalAmt = impl.getTotalDueAmt();
            this.setTotalAmount(totalAmt);
            return totalAmt;
        }
        if("NET DUE".equals(chargeName)){
            XxplCancellationCharge_VOImpl impl = (XxplCancellationCharge_VOImpl)getViewObject();
            totalAmt = impl.getTotalNetDueAmt();
            this.setTotalAmount(totalAmt);
            return totalAmt;
        }
        return (BigDecimal) getAttributeInternal(TOTALAMOUNT);   
        
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_AMOUNT using the alias name TotalAmount.
     * @param value value to set the TOTAL_AMOUNT
     */
    public void setTotalAmount(BigDecimal value) {
        setAttributeInternal(TOTALAMOUNT, value);
    }

    /**
     * Gets the attribute value for VAT_AMOUNT using the alias name VatAmount.
     * @return the VAT_AMOUNT
     */
    public BigDecimal getVatAmount() {
        String chargeName = this.getChargeName();
        BigDecimal chargeAmt = new BigDecimal(0);
        BigDecimal taxRate = new BigDecimal(0);
        BigDecimal vatAmt = new BigDecimal(0);
        if("RENT_INCOME_DAY_CONSUM".equals(chargeName) ||
           "TWO_MONTH_PENALTY".equals(chargeName) || 
           "CHEQUE_WITHDRA_FEE".equals(chargeName)||
            "ACCESS_CARD".equals(chargeName))  
        {
            chargeAmt = this.getAmount()!=null?this.getAmount():new BigDecimal(0);
            taxRate = this.getTaxRate()!=null?this.getTaxRate():new BigDecimal(0);
            vatAmt = (taxRate.multiply(chargeAmt).divide(new BigDecimal(100)));
            return vatAmt;
        }
        if("TOTAL".equals(chargeName)){
            XxplCancellationCharge_VOImpl impl = (XxplCancellationCharge_VOImpl)getViewObject();
            vatAmt = impl.getTaxSumAmt();
            return vatAmt;
        }
           return (BigDecimal) getAttributeInternal(VATAMOUNT);   
    }

    /**
     * Sets <code>value</code> as attribute value for VAT_AMOUNT using the alias name VatAmount.
     * @param value value to set the VAT_AMOUNT
     */
    public void setVatAmount(BigDecimal value) {
        setAttributeInternal(VATAMOUNT, value);
    }

    /**
     * Gets the attribute value for INTERFACE_STATUS using the alias name InterfaceStatus.
     * @return the INTERFACE_STATUS
     */
    public String getInterfaceStatus() {
        return (String) getAttributeInternal(INTERFACESTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for INTERFACE_STATUS using the alias name InterfaceStatus.
     * @param value value to set the INTERFACE_STATUS
     */
    public void setInterfaceStatus(String value) {
        setAttributeInternal(INTERFACESTATUS, value);
    }

    /**
     * Gets the attribute value for INVOICE_NUMBER using the alias name InvoiceNumber.
     * @return the INVOICE_NUMBER
     */
    public String getInvoiceNumber() {
        return (String) getAttributeInternal(INVOICENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICE_NUMBER using the alias name InvoiceNumber.
     * @param value value to set the INVOICE_NUMBER
     */
    public void setInvoiceNumber(String value) {
        setAttributeInternal(INVOICENUMBER, value);
    }

    /**
     * Gets the attribute value for ERROR_MSG using the alias name ErrorMsg.
     * @return the ERROR_MSG
     */
    public String getErrorMsg() {
        return (String) getAttributeInternal(ERRORMSG);
    }

    /**
     * Sets <code>value</code> as attribute value for ERROR_MSG using the alias name ErrorMsg.
     * @param value value to set the ERROR_MSG
     */
    public void setErrorMsg(String value) {
        setAttributeInternal(ERRORMSG, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_TRX_ID using the alias name CustomerTrxId.
     * @return the CUSTOMER_TRX_ID
     */
    public BigDecimal getCustomerTrxId() {
        return (BigDecimal) getAttributeInternal(CUSTOMERTRXID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_TRX_ID using the alias name CustomerTrxId.
     * @param value value to set the CUSTOMER_TRX_ID
     */
    public void setCustomerTrxId(BigDecimal value) {
        setAttributeInternal(CUSTOMERTRXID, value);
    }

    /**
     * Gets the attribute value for CANCEL_CHAR_TYPE using the alias name CancelCharType.
     * @return the CANCEL_CHAR_TYPE
     */
    public String getCancelCharType() {
        return (String) getAttributeInternal(CANCELCHARTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for CANCEL_CHAR_TYPE using the alias name CancelCharType.
     * @param value value to set the CANCEL_CHAR_TYPE
     */
    public void setCancelCharType(String value) {
        setAttributeInternal(CANCELCHARTYPE, value);
    }

    /**
     * Gets the attribute value for CAN_AMT_APPLY using the alias name CanAmtApply.
     * @return the CAN_AMT_APPLY
     */
    public BigDecimal getCanAmtApply() {
        return (BigDecimal) getAttributeInternal(CANAMTAPPLY);
    }

    /**
     * Sets <code>value</code> as attribute value for CAN_AMT_APPLY using the alias name CanAmtApply.
     * @param value value to set the CAN_AMT_APPLY
     */
    public void setCanAmtApply(BigDecimal value) {
        setAttributeInternal(CANAMTAPPLY, value);
    }

    /**
     * Gets the attribute value for CAN_FLAG using the alias name CanFlag.
     * @return the CAN_FLAG
     */
    public String getCanFlag() {
        return (String) getAttributeInternal(CANFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for CAN_FLAG using the alias name CanFlag.
     * @param value value to set the CAN_FLAG
     */
    public void setCanFlag(String value) {
        setAttributeInternal(CANFLAG, value);
    }

    /**
     * Gets the attribute value for CAN_GL_DATE using the alias name CanGlDate.
     * @return the CAN_GL_DATE
     */
    public Date getCanGlDate() {
        return (Date) getAttributeInternal(CANGLDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CAN_GL_DATE using the alias name CanGlDate.
     * @param value value to set the CAN_GL_DATE
     */
    public void setCanGlDate(Date value) {
        setAttributeInternal(CANGLDATE, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CancellatinCharge_LOOKUP.
     */
    public RowSet getCancellatinCharge_LOOKUP() {
        return (RowSet)getAttributeInternal(CANCELLATINCHARGE_LOOKUP);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Tax_LOOKUP.
     */
    public RowSet getTax_LOOKUP() {
        return (RowSet)getAttributeInternal(TAX_LOOKUP);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
