package custom.lease.model.View;

import custom.lease.model.Entity.XxplBookingCustomer_EOImpl;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 19 19:14:28 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxplBookingCustomer_VORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Attribute1 {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        Attribute16 {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getAttribute16();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute16((String)value);
            }
        }
        ,
        Attribute17 {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getAttribute17();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute17((String)value);
            }
        }
        ,
        Attribute18 {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getAttribute18();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute18((String)value);
            }
        }
        ,
        Attribute19 {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getAttribute19();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute19((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute20 {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getAttribute20();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute20((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        AttributeCategory {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getAttributeCategory();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttributeCategory((String)value);
            }
        }
        ,
        BillToSiteId {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getBillToSiteId();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setBillToSiteId((BigDecimal)value);
            }
        }
        ,
        BookingCustId {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getBookingCustId();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setBookingCustId((Number)value);
            }
        }
        ,
        BookingHdrId {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getBookingHdrId();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setBookingHdrId((Number)value);
            }
        }
        ,
        CreatedBy {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setCreationDate((Timestamp)value);
            }
        }
        ,
        CustContactId {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getCustContactId();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setCustContactId((BigDecimal)value);
            }
        }
        ,
        CustId {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getCustId();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setCustId((BigDecimal)value);
            }
        }
        ,
        Description {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getDescription();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setLastUpdateDate((Timestamp)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setLastUpdateLogin((String)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        ObjectVersion {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getObjectVersion();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setObjectVersion((BigDecimal)value);
            }
        }
        ,
        PrimaryYn {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getPrimaryYn();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setPrimaryYn((String)value);
            }
        }
        ,
        ShipToSiteId {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getShipToSiteId();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setShipToSiteId((BigDecimal)value);
            }
        }
        ,
        OrgId {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setOrgId((String)value);
            }
        }
        ,
        Customer_Trans {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getCustomer_Trans();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setCustomer_Trans((String)value);
            }
        }
        ,
        PrimaryFlag {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getPrimaryFlag();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setPrimaryFlag((Boolean)value);
            }
        }
        ,
        XxplBookingJoinCustomer_VO {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getXxplBookingJoinCustomer_VO();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        XxplBookingHeader_VO {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getXxplBookingHeader_VO();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        XXSTG_CUSTOMER_ROVO {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getXXSTG_CUSTOMER_ROVO();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        XXSTG_CUST_CONTACT {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getXXSTG_CUST_CONTACT();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CUSTOMER_SITE_ROVO {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getCUSTOMER_SITE_ROVO();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CUSTOMER_V_ROVO_Ref {
            public Object get(XxplBookingCustomer_VORowImpl obj) {
                return obj.getCUSTOMER_V_ROVO_Ref();
            }

            public void put(XxplBookingCustomer_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(XxplBookingCustomer_VORowImpl object);

        public abstract void put(XxplBookingCustomer_VORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int ATTRIBUTE16 = AttributesEnum.Attribute16.index();
    public static final int ATTRIBUTE17 = AttributesEnum.Attribute17.index();
    public static final int ATTRIBUTE18 = AttributesEnum.Attribute18.index();
    public static final int ATTRIBUTE19 = AttributesEnum.Attribute19.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE20 = AttributesEnum.Attribute20.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTECATEGORY = AttributesEnum.AttributeCategory.index();
    public static final int BILLTOSITEID = AttributesEnum.BillToSiteId.index();
    public static final int BOOKINGCUSTID = AttributesEnum.BookingCustId.index();
    public static final int BOOKINGHDRID = AttributesEnum.BookingHdrId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CUSTCONTACTID = AttributesEnum.CustContactId.index();
    public static final int CUSTID = AttributesEnum.CustId.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int OBJECTVERSION = AttributesEnum.ObjectVersion.index();
    public static final int PRIMARYYN = AttributesEnum.PrimaryYn.index();
    public static final int SHIPTOSITEID = AttributesEnum.ShipToSiteId.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int CUSTOMER_TRANS = AttributesEnum.Customer_Trans.index();
    public static final int PRIMARYFLAG = AttributesEnum.PrimaryFlag.index();
    public static final int XXPLBOOKINGJOINCUSTOMER_VO = AttributesEnum.XxplBookingJoinCustomer_VO.index();
    public static final int XXPLBOOKINGHEADER_VO = AttributesEnum.XxplBookingHeader_VO.index();
    public static final int XXSTG_CUSTOMER_ROVO = AttributesEnum.XXSTG_CUSTOMER_ROVO.index();
    public static final int XXSTG_CUST_CONTACT = AttributesEnum.XXSTG_CUST_CONTACT.index();
    public static final int CUSTOMER_SITE_ROVO = AttributesEnum.CUSTOMER_SITE_ROVO.index();
    public static final int CUSTOMER_V_ROVO_REF = AttributesEnum.CUSTOMER_V_ROVO_Ref.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxplBookingCustomer_VORowImpl() {
    }

    /**
     * Gets XxplBookingCustomer_EO entity object.
     * @return the XxplBookingCustomer_EO
     */
    public XxplBookingCustomer_EOImpl getXxplBookingCustomer_EO() {
        return (XxplBookingCustomer_EOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE16 using the alias name Attribute16.
     * @return the ATTRIBUTE16
     */
    public String getAttribute16() {
        return (String)getAttributeInternal(ATTRIBUTE16);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE16 using the alias name Attribute16.
     * @param value value to set the ATTRIBUTE16
     */
    public void setAttribute16(String value) {
        setAttributeInternal(ATTRIBUTE16, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE17 using the alias name Attribute17.
     * @return the ATTRIBUTE17
     */
    public String getAttribute17() {
        return (String)getAttributeInternal(ATTRIBUTE17);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE17 using the alias name Attribute17.
     * @param value value to set the ATTRIBUTE17
     */
    public void setAttribute17(String value) {
        setAttributeInternal(ATTRIBUTE17, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE18 using the alias name Attribute18.
     * @return the ATTRIBUTE18
     */
    public String getAttribute18() {
        return (String)getAttributeInternal(ATTRIBUTE18);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE18 using the alias name Attribute18.
     * @param value value to set the ATTRIBUTE18
     */
    public void setAttribute18(String value) {
        setAttributeInternal(ATTRIBUTE18, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE19 using the alias name Attribute19.
     * @return the ATTRIBUTE19
     */
    public String getAttribute19() {
        return (String)getAttributeInternal(ATTRIBUTE19);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE19 using the alias name Attribute19.
     * @param value value to set the ATTRIBUTE19
     */
    public void setAttribute19(String value) {
        setAttributeInternal(ATTRIBUTE19, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE20 using the alias name Attribute20.
     * @return the ATTRIBUTE20
     */
    public String getAttribute20() {
        return (String)getAttributeInternal(ATTRIBUTE20);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE20 using the alias name Attribute20.
     * @param value value to set the ATTRIBUTE20
     */
    public void setAttribute20(String value) {
        setAttributeInternal(ATTRIBUTE20, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @return the ATTRIBUTE_CATEGORY
     */
    public String getAttributeCategory() {
        return (String)getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @param value value to set the ATTRIBUTE_CATEGORY
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for BILL_TO_SITE_ID using the alias name BillToSiteId.
     * @return the BILL_TO_SITE_ID
     */
    public BigDecimal getBillToSiteId() {
        return (BigDecimal)getAttributeInternal(BILLTOSITEID);
    }

    /**
     * Sets <code>value</code> as attribute value for BILL_TO_SITE_ID using the alias name BillToSiteId.
     * @param value value to set the BILL_TO_SITE_ID
     */
    public void setBillToSiteId(BigDecimal value) {
        setAttributeInternal(BILLTOSITEID, value);
    }

    /**
     * Gets the attribute value for BOOKING_CUST_ID using the alias name BookingCustId.
     * @return the BOOKING_CUST_ID
     */
    public Number getBookingCustId() {
        return (Number)getAttributeInternal(BOOKINGCUSTID);
    }

    /**
     * Sets <code>value</code> as attribute value for BOOKING_CUST_ID using the alias name BookingCustId.
     * @param value value to set the BOOKING_CUST_ID
     */
    public void setBookingCustId(Number value) {
        setAttributeInternal(BOOKINGCUSTID, value);
    }

    /**
     * Gets the attribute value for BOOKING_HDR_ID using the alias name BookingHdrId.
     * @return the BOOKING_HDR_ID
     */
    public Number getBookingHdrId() {
        return (Number)getAttributeInternal(BOOKINGHDRID);
    }

    /**
     * Sets <code>value</code> as attribute value for BOOKING_HDR_ID using the alias name BookingHdrId.
     * @param value value to set the BOOKING_HDR_ID
     */
    public void setBookingHdrId(Number value) {
        setAttributeInternal(BOOKINGHDRID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CUST_CONTACT_ID using the alias name CustContactId.
     * @return the CUST_CONTACT_ID
     */
    public BigDecimal getCustContactId() {
        return (BigDecimal)getAttributeInternal(CUSTCONTACTID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_CONTACT_ID using the alias name CustContactId.
     * @param value value to set the CUST_CONTACT_ID
     */
    public void setCustContactId(BigDecimal value) {
        setAttributeInternal(CUSTCONTACTID, value);
    }

    /**
     * Gets the attribute value for CUST_ID using the alias name CustId.
     * @return the CUST_ID
     */
    public BigDecimal getCustId() {
        return (BigDecimal)getAttributeInternal(CUSTID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_ID using the alias name CustId.
     * @param value value to set the CUST_ID
     */
    public void setCustId(BigDecimal value) {
        setAttributeInternal(CUSTID, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String)getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION using the alias name ObjectVersion.
     * @return the OBJECT_VERSION
     */
    public BigDecimal getObjectVersion() {
        return (BigDecimal)getAttributeInternal(OBJECTVERSION);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION using the alias name ObjectVersion.
     * @param value value to set the OBJECT_VERSION
     */
    public void setObjectVersion(BigDecimal value) {
        setAttributeInternal(OBJECTVERSION, value);
    }

    /**
     * Gets the attribute value for PRIMARY_YN using the alias name PrimaryYn.
     * @return the PRIMARY_YN
     */
    public String getPrimaryYn() {
        return (String)getAttributeInternal(PRIMARYYN);
    }

    /**
     * Sets <code>value</code> as attribute value for PRIMARY_YN using the alias name PrimaryYn.
     * @param value value to set the PRIMARY_YN
     */
    public void setPrimaryYn(String value) {
        setAttributeInternal(PRIMARYYN, value);
    }

    /**
     * Gets the attribute value for SHIP_TO_SITE_ID using the alias name ShipToSiteId.
     * @return the SHIP_TO_SITE_ID
     */
    public BigDecimal getShipToSiteId() {
        return (BigDecimal)getAttributeInternal(SHIPTOSITEID);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_TO_SITE_ID using the alias name ShipToSiteId.
     * @param value value to set the SHIP_TO_SITE_ID
     */
    public void setShipToSiteId(BigDecimal value) {
        setAttributeInternal(SHIPTOSITEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrgId.
     * @return the OrgId
     */
    public String getOrgId() {
        Row currHdr = getXxplBookingHeader_VO();
        String orgId = currHdr.getAttribute("OrgId").toString();
        return orgId;
        //      return (String) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrgId.
     * @param value value to set the  OrgId
     */
    public void setOrgId(String value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Customer_Trans.
     * @return the Customer_Trans
     */
    public String getCustomer_Trans() {
//        BigDecimal custId = this.getCustId();
//        String custName = "";
//        if (custId != null) {
//            ViewRowSetImpl vo = (ViewRowSetImpl)getCUSTOMER_V_ROVO_Ref();
//            ViewObject vo1 = vo.getViewObject();
//            ViewCriteria vc1 = vo1.createViewCriteria();
//            ViewCriteriaRow vcr = vc1.createViewCriteriaRow();
//            vcr.setAttribute("CustId", custId);
//            vc1.addRow(vcr);
//            vo1.applyViewCriteria(vc1);
//            vo1.executeQuery();
//            Row rw = vo1.first();
//            if (rw != null) {
//                custName = (String)rw.getAttribute("CustomerName");
//            }
//            vo1.applyViewCriteria(null);
//            vo1.executeQuery();
//            return custName;
//        } else {
            return (String)getAttributeInternal(CUSTOMER_TRANS);
//        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Customer_Trans.
     * @param value value to set the  Customer_Trans
     */
    public void setCustomer_Trans(String value) {
        setAttributeInternal(CUSTOMER_TRANS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PrimaryFlag.
     * @return the PrimaryFlag
     */
    public Boolean getPrimaryFlag() {
        Boolean flag = false;
        if (this.getPrimaryYn() != null &&
            this.getPrimaryYn().equalsIgnoreCase("Y")) {
            flag = true;
        } else {
            flag = false;
        }
        return flag;
        //        return (Boolean) getAttributeInternal(PRIMARYFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PrimaryFlag.
     * @param value value to set the  PrimaryFlag
     */
    public void setPrimaryFlag(Boolean value) {
        if (value) {
            this.setPrimaryYn("Y");
        } else {
            this.setPrimaryYn("N");
        }
        setAttributeInternal(PRIMARYFLAG, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XxplBookingJoinCustomer_VO.
     */
    public RowIterator getXxplBookingJoinCustomer_VO() {
        return (RowIterator)getAttributeInternal(XXPLBOOKINGJOINCUSTOMER_VO);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link XxplBookingHeader_VO.
     */
    public Row getXxplBookingHeader_VO() {
        return (Row)getAttributeInternal(XXPLBOOKINGHEADER_VO);
    }

    /**
     * Sets the master-detail link XxplBookingHeader_VO between this object and <code>value</code>.
     */
    public void setXxplBookingHeader_VO(Row value) {
        setAttributeInternal(XXPLBOOKINGHEADER_VO, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XXSTG_CUSTOMER_ROVO.
     */
    public RowSet getXXSTG_CUSTOMER_ROVO() {
        return (RowSet)getAttributeInternal(XXSTG_CUSTOMER_ROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XXSTG_CUST_CONTACT.
     */
    public RowSet getXXSTG_CUST_CONTACT() {
        return (RowSet)getAttributeInternal(XXSTG_CUST_CONTACT);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CUSTOMER_SITE_ROVO.
     */
    public RowSet getCUSTOMER_SITE_ROVO() {
        return (RowSet)getAttributeInternal(CUSTOMER_SITE_ROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CUSTOMER_V_ROVO_Ref.
     */
    public RowSet getCUSTOMER_V_ROVO_Ref() {
        return (RowSet)getAttributeInternal(CUSTOMER_V_ROVO_REF);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
