package custom.lease.model.View;

import custom.lease.model.Entity.XxplInvoiceHeaderImpl;

import java.math.BigDecimal;

import java.sql.Clob;
import java.sql.Date;
import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 16 12:40:27 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxplInvoiceHeaderRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        AcntRule {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getAcntRule();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setAcntRule((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        AttributeCategory {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getAttributeCategory();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setAttributeCategory((String)value);
            }
        }
        ,
        BookingId {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getBookingId();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setBookingId((BigDecimal)value);
            }
        }
        ,
        BookingNumber {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getBookingNumber();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setBookingNumber((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setCreationDate((Timestamp)value);
            }
        }
        ,
        CurrencyCode {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getCurrencyCode();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setCurrencyCode((String)value);
            }
        }
        ,
        CustId {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getCustId();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setCustId((BigDecimal)value);
            }
        }
        ,
        CustSiteId {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getCustSiteId();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setCustSiteId((BigDecimal)value);
            }
        }
        ,
        CustomerTrxId {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getCustomerTrxId();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setCustomerTrxId((BigDecimal)value);
            }
        }
        ,
        CustomerTrxNumber {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getCustomerTrxNumber();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setCustomerTrxNumber((String)value);
            }
        }
        ,
        DueDate {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getDueDate();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setDueDate((Date)value);
            }
        }
        ,
        ExchangeRate {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getExchangeRate();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setExchangeRate((BigDecimal)value);
            }
        }
        ,
        FuncId {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getFuncId();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setFuncId((BigDecimal)value);
            }
        }
        ,
        GlDate {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getGlDate();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setGlDate((Date)value);
            }
        }
        ,
        InterfaceErrorMsg {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getInterfaceErrorMsg();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setInterfaceErrorMsg((Clob)value);
            }
        }
        ,
        InterfaceStatus {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getInterfaceStatus();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setInterfaceStatus((String)value);
            }
        }
        ,
        InvoiceClass {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getInvoiceClass();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setInvoiceClass((String)value);
            }
        }
        ,
        InvoiceDate {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getInvoiceDate();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setInvoiceDate((Date)value);
            }
        }
        ,
        InvoiceId {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getInvoiceId();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setInvoiceId((Number)value);
            }
        }
        ,
        InvoiceNumber {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getInvoiceNumber();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setInvoiceNumber((String)value);
            }
        }
        ,
        InvoicingRule {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getInvoicingRule();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setInvoicingRule((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setLastUpdateDate((Timestamp)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setLastUpdateLogin((String)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        ObjectVersion {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getObjectVersion();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setObjectVersion((BigDecimal)value);
            }
        }
        ,
        OfferId {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getOfferId();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setOfferId((BigDecimal)value);
            }
        }
        ,
        OfferNumber {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getOfferNumber();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setOfferNumber((String)value);
            }
        }
        ,
        OrgId {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getOrgId();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        PaymentTerms {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getPaymentTerms();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setPaymentTerms((BigDecimal)value);
            }
        }
        ,
        RuleEndDate {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getRuleEndDate();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setRuleEndDate((Date)value);
            }
        }
        ,
        RuleStartDate {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getRuleStartDate();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setRuleStartDate((Date)value);
            }
        }
        ,
        SaleLeaseNumber {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getSaleLeaseNumber();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setSaleLeaseNumber((String)value);
            }
        }
        ,
        Status {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getStatus();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        TrxSource {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getTrxSource();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setTrxSource((String)value);
            }
        }
        ,
        TrxType {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getTrxType();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setTrxType((String)value);
            }
        }
        ,
        BusinessUnitTrans {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getBusinessUnitTrans();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setBusinessUnitTrans((String)value);
            }
        }
        ,
        CustomerSIte {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getCustomerSIte();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setCustomerSIte((String)value);
            }
        }
        ,
        CustomerSiteIdTrans {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getCustomerSiteIdTrans();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setCustomerSiteIdTrans((String)value);
            }
        }
        ,
        CurrencyCodeTrans {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getCurrencyCodeTrans();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setCurrencyCodeTrans((String)value);
            }
        }
        ,
        ProjectIdTrans {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getProjectIdTrans();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setProjectIdTrans((BigDecimal)value);
            }
        }
        ,
        TotalLineAmount {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getTotalLineAmount();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setTotalLineAmount((BigDecimal)value);
            }
        }
        ,
        CustomerNameTrans {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getCustomerNameTrans();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setCustomerNameTrans((String)value);
            }
        }
        ,
        XxplInvoiceLineVO {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getXxplInvoiceLineVO();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        XXSTG_ORGANIZATIONS_ROVO {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getXXSTG_ORGANIZATIONS_ROVO();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        XXSTG_CUSTOMER_V_ROVO {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getXXSTG_CUSTOMER_V_ROVO();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        XXFND_CURRENCY_ROVO {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getXXFND_CURRENCY_ROVO();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BookingROVOLOV {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getBookingROVOLOV();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        InvoiceNumberROVO {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getInvoiceNumberROVO();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BookingBasedCustomerROVO {
            public Object get(XxplInvoiceHeaderRowImpl obj) {
                return obj.getBookingBasedCustomerROVO();
            }

            public void put(XxplInvoiceHeaderRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(XxplInvoiceHeaderRowImpl object);

        public abstract void put(XxplInvoiceHeaderRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ACNTRULE = AttributesEnum.AcntRule.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTECATEGORY = AttributesEnum.AttributeCategory.index();
    public static final int BOOKINGID = AttributesEnum.BookingId.index();
    public static final int BOOKINGNUMBER = AttributesEnum.BookingNumber.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CURRENCYCODE = AttributesEnum.CurrencyCode.index();
    public static final int CUSTID = AttributesEnum.CustId.index();
    public static final int CUSTSITEID = AttributesEnum.CustSiteId.index();
    public static final int CUSTOMERTRXID = AttributesEnum.CustomerTrxId.index();
    public static final int CUSTOMERTRXNUMBER = AttributesEnum.CustomerTrxNumber.index();
    public static final int DUEDATE = AttributesEnum.DueDate.index();
    public static final int EXCHANGERATE = AttributesEnum.ExchangeRate.index();
    public static final int FUNCID = AttributesEnum.FuncId.index();
    public static final int GLDATE = AttributesEnum.GlDate.index();
    public static final int INTERFACEERRORMSG = AttributesEnum.InterfaceErrorMsg.index();
    public static final int INTERFACESTATUS = AttributesEnum.InterfaceStatus.index();
    public static final int INVOICECLASS = AttributesEnum.InvoiceClass.index();
    public static final int INVOICEDATE = AttributesEnum.InvoiceDate.index();
    public static final int INVOICEID = AttributesEnum.InvoiceId.index();
    public static final int INVOICENUMBER = AttributesEnum.InvoiceNumber.index();
    public static final int INVOICINGRULE = AttributesEnum.InvoicingRule.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int OBJECTVERSION = AttributesEnum.ObjectVersion.index();
    public static final int OFFERID = AttributesEnum.OfferId.index();
    public static final int OFFERNUMBER = AttributesEnum.OfferNumber.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int PAYMENTTERMS = AttributesEnum.PaymentTerms.index();
    public static final int RULEENDDATE = AttributesEnum.RuleEndDate.index();
    public static final int RULESTARTDATE = AttributesEnum.RuleStartDate.index();
    public static final int SALELEASENUMBER = AttributesEnum.SaleLeaseNumber.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int TRXSOURCE = AttributesEnum.TrxSource.index();
    public static final int TRXTYPE = AttributesEnum.TrxType.index();
    public static final int BUSINESSUNITTRANS = AttributesEnum.BusinessUnitTrans.index();
    public static final int CUSTOMERSITE = AttributesEnum.CustomerSIte.index();
    public static final int CUSTOMERSITEIDTRANS = AttributesEnum.CustomerSiteIdTrans.index();
    public static final int CURRENCYCODETRANS = AttributesEnum.CurrencyCodeTrans.index();
    public static final int PROJECTIDTRANS = AttributesEnum.ProjectIdTrans.index();
    public static final int TOTALLINEAMOUNT = AttributesEnum.TotalLineAmount.index();
    public static final int CUSTOMERNAMETRANS = AttributesEnum.CustomerNameTrans.index();
    public static final int XXPLINVOICELINEVO = AttributesEnum.XxplInvoiceLineVO.index();
    public static final int XXSTG_ORGANIZATIONS_ROVO = AttributesEnum.XXSTG_ORGANIZATIONS_ROVO.index();
    public static final int XXSTG_CUSTOMER_V_ROVO = AttributesEnum.XXSTG_CUSTOMER_V_ROVO.index();
    public static final int XXFND_CURRENCY_ROVO = AttributesEnum.XXFND_CURRENCY_ROVO.index();
    public static final int BOOKINGROVOLOV = AttributesEnum.BookingROVOLOV.index();
    public static final int INVOICENUMBERROVO = AttributesEnum.InvoiceNumberROVO.index();
    public static final int BOOKINGBASEDCUSTOMERROVO = AttributesEnum.BookingBasedCustomerROVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxplInvoiceHeaderRowImpl() {
    }

    /**
     * Gets XxplInvoiceHeader entity object.
     * @return the XxplInvoiceHeader
     */
    public XxplInvoiceHeaderImpl getXxplInvoiceHeader() {
        return (XxplInvoiceHeaderImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for ACNT_RULE using the alias name AcntRule.
     * @return the ACNT_RULE
     */
    public String getAcntRule() {
        return (String) getAttributeInternal(ACNTRULE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACNT_RULE using the alias name AcntRule.
     * @param value value to set the ACNT_RULE
     */
    public void setAcntRule(String value) {
        setAttributeInternal(ACNTRULE, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @return the ATTRIBUTE_CATEGORY
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @param value value to set the ATTRIBUTE_CATEGORY
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for BOOKING_ID using the alias name BookingId.
     * @return the BOOKING_ID
     */
    public BigDecimal getBookingId() {
        return (BigDecimal) getAttributeInternal(BOOKINGID);
    }

    /**
     * Sets <code>value</code> as attribute value for BOOKING_ID using the alias name BookingId.
     * @param value value to set the BOOKING_ID
     */
    public void setBookingId(BigDecimal value) {
        setAttributeInternal(BOOKINGID, value);
    }

    /**
     * Gets the attribute value for BOOKING_NUMBER using the alias name BookingNumber.
     * @return the BOOKING_NUMBER
     */
    public String getBookingNumber() {
        return (String) getAttributeInternal(BOOKINGNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for BOOKING_NUMBER using the alias name BookingNumber.
     * @param value value to set the BOOKING_NUMBER
     */
    public void setBookingNumber(String value) {
        setAttributeInternal(BOOKINGNUMBER, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CURRENCY_CODE using the alias name CurrencyCode.
     * @return the CURRENCY_CODE
     */
    public String getCurrencyCode() {
        return (String) getAttributeInternal(CURRENCYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENCY_CODE using the alias name CurrencyCode.
     * @param value value to set the CURRENCY_CODE
     */
    public void setCurrencyCode(String value) {
        setAttributeInternal(CURRENCYCODE, value);
    }

    /**
     * Gets the attribute value for CUST_ID using the alias name CustId.
     * @return the CUST_ID
     */
    public BigDecimal getCustId() {
        return (BigDecimal) getAttributeInternal(CUSTID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_ID using the alias name CustId.
     * @param value value to set the CUST_ID
     */
    public void setCustId(BigDecimal value) {
        setAttributeInternal(CUSTID, value);
    }

    /**
     * Gets the attribute value for CUST_SITE_ID using the alias name CustSiteId.
     * @return the CUST_SITE_ID
     */
    public BigDecimal getCustSiteId() {
        return (BigDecimal) getAttributeInternal(CUSTSITEID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_SITE_ID using the alias name CustSiteId.
     * @param value value to set the CUST_SITE_ID
     */
    public void setCustSiteId(BigDecimal value) {
        setAttributeInternal(CUSTSITEID, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_TRX_ID using the alias name CustomerTrxId.
     * @return the CUSTOMER_TRX_ID
     */
    public BigDecimal getCustomerTrxId() {
        return (BigDecimal) getAttributeInternal(CUSTOMERTRXID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_TRX_ID using the alias name CustomerTrxId.
     * @param value value to set the CUSTOMER_TRX_ID
     */
    public void setCustomerTrxId(BigDecimal value) {
        setAttributeInternal(CUSTOMERTRXID, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_TRX_NUMBER using the alias name CustomerTrxNumber.
     * @return the CUSTOMER_TRX_NUMBER
     */
    public String getCustomerTrxNumber() {
        return (String) getAttributeInternal(CUSTOMERTRXNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_TRX_NUMBER using the alias name CustomerTrxNumber.
     * @param value value to set the CUSTOMER_TRX_NUMBER
     */
    public void setCustomerTrxNumber(String value) {
        setAttributeInternal(CUSTOMERTRXNUMBER, value);
    }

    /**
     * Gets the attribute value for DUE_DATE using the alias name DueDate.
     * @return the DUE_DATE
     */
    public Date getDueDate() {
        return (Date) getAttributeInternal(DUEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DUE_DATE using the alias name DueDate.
     * @param value value to set the DUE_DATE
     */
    public void setDueDate(Date value) {
        setAttributeInternal(DUEDATE, value);
    }

    /**
     * Gets the attribute value for EXCHANGE_RATE using the alias name ExchangeRate.
     * @return the EXCHANGE_RATE
     */
    public BigDecimal getExchangeRate() {
        return (BigDecimal) getAttributeInternal(EXCHANGERATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EXCHANGE_RATE using the alias name ExchangeRate.
     * @param value value to set the EXCHANGE_RATE
     */
    public void setExchangeRate(BigDecimal value) {
        setAttributeInternal(EXCHANGERATE, value);
    }

    /**
     * Gets the attribute value for FUNC_ID using the alias name FuncId.
     * @return the FUNC_ID
     */
    public BigDecimal getFuncId() {
        return (BigDecimal) getAttributeInternal(FUNCID);
    }

    /**
     * Sets <code>value</code> as attribute value for FUNC_ID using the alias name FuncId.
     * @param value value to set the FUNC_ID
     */
    public void setFuncId(BigDecimal value) {
        setAttributeInternal(FUNCID, value);
    }

    /**
     * Gets the attribute value for GL_DATE using the alias name GlDate.
     * @return the GL_DATE
     */
    public Date getGlDate() {
        return (Date) getAttributeInternal(GLDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GL_DATE using the alias name GlDate.
     * @param value value to set the GL_DATE
     */
    public void setGlDate(Date value) {
        setAttributeInternal(GLDATE, value);
    }

    /**
     * Gets the attribute value for INTERFACE_ERROR_MSG using the alias name InterfaceErrorMsg.
     * @return the INTERFACE_ERROR_MSG
     */
    public Clob getInterfaceErrorMsg() {
        return (Clob) getAttributeInternal(INTERFACEERRORMSG);
    }

    /**
     * Sets <code>value</code> as attribute value for INTERFACE_ERROR_MSG using the alias name InterfaceErrorMsg.
     * @param value value to set the INTERFACE_ERROR_MSG
     */
    public void setInterfaceErrorMsg(Clob value) {
        setAttributeInternal(INTERFACEERRORMSG, value);
    }

    /**
     * Gets the attribute value for INTERFACE_STATUS using the alias name InterfaceStatus.
     * @return the INTERFACE_STATUS
     */
    public String getInterfaceStatus() {
        return (String) getAttributeInternal(INTERFACESTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for INTERFACE_STATUS using the alias name InterfaceStatus.
     * @param value value to set the INTERFACE_STATUS
     */
    public void setInterfaceStatus(String value) {
        setAttributeInternal(INTERFACESTATUS, value);
    }

    /**
     * Gets the attribute value for INVOICE_CLASS using the alias name InvoiceClass.
     * @return the INVOICE_CLASS
     */
    public String getInvoiceClass() {
        return (String) getAttributeInternal(INVOICECLASS);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICE_CLASS using the alias name InvoiceClass.
     * @param value value to set the INVOICE_CLASS
     */
    public void setInvoiceClass(String value) {
        setAttributeInternal(INVOICECLASS, value);
    }

    /**
     * Gets the attribute value for INVOICE_DATE using the alias name InvoiceDate.
     * @return the INVOICE_DATE
     */
    public Date getInvoiceDate() {
        return (Date) getAttributeInternal(INVOICEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICE_DATE using the alias name InvoiceDate.
     * @param value value to set the INVOICE_DATE
     */
    public void setInvoiceDate(Date value) {
        setAttributeInternal(INVOICEDATE, value);
    }

    /**
     * Gets the attribute value for INVOICE_ID using the alias name InvoiceId.
     * @return the INVOICE_ID
     */
    public Number getInvoiceId() {
        return (Number)getAttributeInternal(INVOICEID);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICE_ID using the alias name InvoiceId.
     * @param value value to set the INVOICE_ID
     */
    public void setInvoiceId(Number value) {
        setAttributeInternal(INVOICEID, value);
    }

    /**
     * Gets the attribute value for INVOICE_NUMBER using the alias name InvoiceNumber.
     * @return the INVOICE_NUMBER
     */
    public String getInvoiceNumber() {
        return (String) getAttributeInternal(INVOICENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICE_NUMBER using the alias name InvoiceNumber.
     * @param value value to set the INVOICE_NUMBER
     */
    public void setInvoiceNumber(String value) {
        setAttributeInternal(INVOICENUMBER, value);
    }

    /**
     * Gets the attribute value for INVOICING_RULE using the alias name InvoicingRule.
     * @return the INVOICING_RULE
     */
    public String getInvoicingRule() {
        return (String) getAttributeInternal(INVOICINGRULE);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICING_RULE using the alias name InvoicingRule.
     * @param value value to set the INVOICING_RULE
     */
    public void setInvoicingRule(String value) {
        setAttributeInternal(INVOICINGRULE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION using the alias name ObjectVersion.
     * @return the OBJECT_VERSION
     */
    public BigDecimal getObjectVersion() {
        return (BigDecimal) getAttributeInternal(OBJECTVERSION);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION using the alias name ObjectVersion.
     * @param value value to set the OBJECT_VERSION
     */
    public void setObjectVersion(BigDecimal value) {
        setAttributeInternal(OBJECTVERSION, value);
    }

    /**
     * Gets the attribute value for OFFER_ID using the alias name OfferId.
     * @return the OFFER_ID
     */
    public BigDecimal getOfferId() {
        return (BigDecimal) getAttributeInternal(OFFERID);
    }

    /**
     * Sets <code>value</code> as attribute value for OFFER_ID using the alias name OfferId.
     * @param value value to set the OFFER_ID
     */
    public void setOfferId(BigDecimal value) {
        setAttributeInternal(OFFERID, value);
    }

    /**
     * Gets the attribute value for OFFER_NUMBER using the alias name OfferNumber.
     * @return the OFFER_NUMBER
     */
    public String getOfferNumber() {
        return (String) getAttributeInternal(OFFERNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for OFFER_NUMBER using the alias name OfferNumber.
     * @param value value to set the OFFER_NUMBER
     */
    public void setOfferNumber(String value) {
        setAttributeInternal(OFFERNUMBER, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for PAYMENT_TERMS using the alias name PaymentTerms.
     * @return the PAYMENT_TERMS
     */
    public BigDecimal getPaymentTerms() {
        return (BigDecimal) getAttributeInternal(PAYMENTTERMS);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_TERMS using the alias name PaymentTerms.
     * @param value value to set the PAYMENT_TERMS
     */
    public void setPaymentTerms(BigDecimal value) {
        setAttributeInternal(PAYMENTTERMS, value);
    }

    /**
     * Gets the attribute value for RULE_END_DATE using the alias name RuleEndDate.
     * @return the RULE_END_DATE
     */
    public Date getRuleEndDate() {
        return (Date) getAttributeInternal(RULEENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for RULE_END_DATE using the alias name RuleEndDate.
     * @param value value to set the RULE_END_DATE
     */
    public void setRuleEndDate(Date value) {
        setAttributeInternal(RULEENDDATE, value);
    }

    /**
     * Gets the attribute value for RULE_START_DATE using the alias name RuleStartDate.
     * @return the RULE_START_DATE
     */
    public Date getRuleStartDate() {
        return (Date) getAttributeInternal(RULESTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for RULE_START_DATE using the alias name RuleStartDate.
     * @param value value to set the RULE_START_DATE
     */
    public void setRuleStartDate(Date value) {
        setAttributeInternal(RULESTARTDATE, value);
    }

    /**
     * Gets the attribute value for SALE_LEASE_NUMBER using the alias name SaleLeaseNumber.
     * @return the SALE_LEASE_NUMBER
     */
    public String getSaleLeaseNumber() {
        return (String) getAttributeInternal(SALELEASENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for SALE_LEASE_NUMBER using the alias name SaleLeaseNumber.
     * @param value value to set the SALE_LEASE_NUMBER
     */
    public void setSaleLeaseNumber(String value) {
        setAttributeInternal(SALELEASENUMBER, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for TRX_SOURCE using the alias name TrxSource.
     * @return the TRX_SOURCE
     */
    public String getTrxSource() {
        return (String) getAttributeInternal(TRXSOURCE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRX_SOURCE using the alias name TrxSource.
     * @param value value to set the TRX_SOURCE
     */
    public void setTrxSource(String value) {
        setAttributeInternal(TRXSOURCE, value);
    }

    /**
     * Gets the attribute value for TRX_TYPE using the alias name TrxType.
     * @return the TRX_TYPE
     */
    public String getTrxType() {
        return (String) getAttributeInternal(TRXTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRX_TYPE using the alias name TrxType.
     * @param value value to set the TRX_TYPE
     */
    public void setTrxType(String value) {
        setAttributeInternal(TRXTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BusinessUnitTrans.
     * @return the BusinessUnitTrans
     */
    public String getBusinessUnitTrans() {
        Number buId = null;
        String departmentName = null;
        if (getOrgId() != null) {
            buId = getOrgId();
            Row[] deptRows;
            deptRows =
                    getXXSTG_ORGANIZATIONS_ROVO().getFilteredRows("OrgId", buId);
            if (deptRows.length > 0) {
                departmentName =
                        deptRows[0].getAttribute("OrgName").toString();
            }
            return departmentName;
        } else {
            return (String)getAttributeInternal(BUSINESSUNITTRANS);
        }

    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BusinessUnitTrans.
     * @param value value to set the  BusinessUnitTrans
     */
    public void setBusinessUnitTrans(String value) {
        setAttributeInternal(BUSINESSUNITTRANS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerSIte.
     * @return the CustomerSIte
     */
    public String getCustomerSIte() {
        BigDecimal buId = null;
//        BigDecimal sitdeid = null;
        String departmentName = null;
       if (getCustId() != null) {
           buId = getCustId();
         
            Row[] deptRows;
            deptRows =
                    getXXSTG_CUSTOMER_V_ROVO().getFilteredRows("CustId", buId);
            
            if (deptRows.length > 0) {
                departmentName =
                        deptRows[0].getAttribute("CustomerName").toString();
            }
            return departmentName;
      } else {
            return (String)getAttributeInternal(CUSTOMERSITE);
      }

    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerSIte.
     * @param value value to set the  CustomerSIte
     */
    public void setCustomerSIte(String value) {
        setAttributeInternal(CUSTOMERSITE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerSiteIdTrans.
     * @return the CustomerSiteIdTrans
     */
    public String getCustomerSiteIdTrans() {
        return (String) getAttributeInternal(CUSTOMERSITEIDTRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerSiteIdTrans.
     * @param value value to set the  CustomerSiteIdTrans
     */
    public void setCustomerSiteIdTrans(String value) {
        setAttributeInternal(CUSTOMERSITEIDTRANS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrencyCodeTrans.
     * @return the CurrencyCodeTrans
     */
    public String getCurrencyCodeTrans() {
        String buId = null;
        String departmentName = null;
        Row[] deptRows;
        if (getCurrencyCode() != null) {
            buId = getCurrencyCode();
            deptRows =
                    getXXFND_CURRENCY_ROVO().getFilteredRows("CurrencyValueName",
                                                             buId);
            if (deptRows.length > 0) {
                departmentName =
                        deptRows[0].getAttribute("CurrencyvalueNameDisp").toString();
            }
            return departmentName;
        } else {
            this.setCurrencyCode(getXXFND_CURRENCY_ROVO().first().getAttribute("CurrencyValueName").toString());
           
           return getXXFND_CURRENCY_ROVO().first().getAttribute("CurrencyvalueNameDisp").toString();
//            return (String)getAttributeInternal(CURRENCYCODETRANS);
        }

    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrencyCodeTrans.
     * @param value value to set the  CurrencyCodeTrans
     */
    public void setCurrencyCodeTrans(String value) {
        setAttributeInternal(CURRENCYCODETRANS, value);
    }


    /**
     * Gets the attribute value for the calculated attribute ProjectIdTrans.
     * @return the ProjectIdTrans
     */
    public BigDecimal getProjectIdTrans() {
        return (BigDecimal) getAttributeInternal(PROJECTIDTRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProjectIdTrans.
     * @param value value to set the  ProjectIdTrans
     */
    public void setProjectIdTrans(BigDecimal value) {
        setAttributeInternal(PROJECTIDTRANS, value);
    }


    /**
     * Gets the attribute value for the calculated attribute TotalLineAmount.
     * @return the TotalLineAmount
     */
    public BigDecimal getTotalLineAmount() {
        return (BigDecimal) getAttributeInternal(TOTALLINEAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalLineAmount.
     * @param value value to set the  TotalLineAmount
     */
    public void setTotalLineAmount(BigDecimal value) {
        setAttributeInternal(TOTALLINEAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerNameTrans.
     * @return the CustomerNameTrans
     */
    public String getCustomerNameTrans() {
        return (String) getAttributeInternal(CUSTOMERNAMETRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerNameTrans.
     * @param value value to set the  CustomerNameTrans
     */
    public void setCustomerNameTrans(String value) {
        setAttributeInternal(CUSTOMERNAMETRANS, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XxplInvoiceLineVO.
     */
    public RowIterator getXxplInvoiceLineVO() {
        return (RowIterator)getAttributeInternal(XXPLINVOICELINEVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XXSTG_ORGANIZATIONS_ROVO.
     */
    public RowSet getXXSTG_ORGANIZATIONS_ROVO() {
        return (RowSet)getAttributeInternal(XXSTG_ORGANIZATIONS_ROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XXSTG_CUSTOMER_V_ROVO.
     */
    public RowSet getXXSTG_CUSTOMER_V_ROVO() {
        return (RowSet)getAttributeInternal(XXSTG_CUSTOMER_V_ROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XXFND_CURRENCY_ROVO.
     */
    public RowSet getXXFND_CURRENCY_ROVO() {
        return (RowSet)getAttributeInternal(XXFND_CURRENCY_ROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BookingROVOLOV.
     */
    public RowSet getBookingROVOLOV() {
        return (RowSet)getAttributeInternal(BOOKINGROVOLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> InvoiceNumberROVO.
     */
    public RowSet getInvoiceNumberROVO() {
        return (RowSet)getAttributeInternal(INVOICENUMBERROVO);
    }


    /**
     * Gets the view accessor <code>RowSet</code> BookingBasedCustomerROVO.
     */
    public RowSet getBookingBasedCustomerROVO() {
        return (RowSet)getAttributeInternal(BOOKINGBASEDCUSTOMERROVO);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
