package custom.lease.model.View;

import custom.lease.model.Entity.XxplHeaderEOImpl;

import java.math.BigDecimal;

import java.sql.Date;
import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 09 23:50:29 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxplHeaderRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ActiveYn {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getActiveYn();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setActiveYn((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        AttributeCategory {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getAttributeCategory();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setAttributeCategory((String)value);
            }
        }
        ,
        BuildId {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getBuildId();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setBuildId((Number)value);
            }
        }
        ,
        CreatedBy {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setCreationDate((Timestamp)value);
            }
        }
        ,
        CurrencyCode {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getCurrencyCode();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setCurrencyCode((String)value);
            }
        }
        ,
        Description {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getDescription();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        EndDate {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getEndDate();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setEndDate((Date)value);
            }
        }
        ,
        FlowLevel {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getFlowLevel();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setFlowLevel((BigDecimal)value);
            }
        }
        ,
        FlowStatus {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getFlowStatus();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setFlowStatus((String)value);
            }
        }
        ,
        FlowWith {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getFlowWith();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setFlowWith((BigDecimal)value);
            }
        }
        ,
        FuncId {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getFuncId();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setFuncId((BigDecimal)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setLastUpdateDate((Timestamp)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setLastUpdateLogin((String)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        ObjectVersion {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getObjectVersion();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setObjectVersion((BigDecimal)value);
            }
        }
        ,
        OrgId {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getOrgId();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        PlId {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getPlId();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setPlId((Number)value);
            }
        }
        ,
        PlName {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getPlName();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setPlName((String)value);
            }
        }
        ,
        PlNameTl {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getPlNameTl();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setPlNameTl((String)value);
            }
        }
        ,
        PlNumber {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getPlNumber();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setPlNumber((String)value);
            }
        }
        ,
        PlType {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getPlType();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setPlType((String)value);
            }
        }
        ,
        Priority {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getPriority();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setPriority((BigDecimal)value);
            }
        }
        ,
        PropertyId {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getPropertyId();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setPropertyId((Number)value);
            }
        }
        ,
        RevisedBy {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getRevisedBy();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setRevisedBy((String)value);
            }
        }
        ,
        RevisionDate {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getRevisionDate();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setRevisionDate((Date)value);
            }
        }
        ,
        RevisionNo {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getRevisionNo();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setRevisionNo((BigDecimal)value);
            }
        }
        ,
        StartDate {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getStartDate();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setStartDate((Date)value);
            }
        }
        ,
        Status {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getStatus();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        Usage {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getUsage();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setUsage((String)value);
            }
        }
        ,
        UserGrpId {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getUserGrpId();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setUserGrpId((BigDecimal)value);
            }
        }
        ,
        PropertyIdTrans {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getPropertyIdTrans();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setPropertyIdTrans((String)value);
            }
        }
        ,
        OrgTransId {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getOrgTransId();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setOrgTransId((String)value);
            }
        }
        ,
        BuildingTransID {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getBuildingTransID();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setBuildingTransID((String)value);
            }
        }
        ,
        PltypeTrans {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getPltypeTrans();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setPltypeTrans((String)value);
            }
        }
        ,
        XxplLineVO {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getXxplLineVO();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        XXSTG_ORGANIZATIONS_ROVO {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getXXSTG_ORGANIZATIONS_ROVO();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SearchPropertyFilterROVO {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getSearchPropertyFilterROVO();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SerachBuildingFilterROVO {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getSerachBuildingFilterROVO();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        XXFND_LOOKUP_V_ROVO {
            public Object get(XxplHeaderRowImpl obj) {
                return obj.getXXFND_LOOKUP_V_ROVO();
            }

            public void put(XxplHeaderRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(XxplHeaderRowImpl object);

        public abstract void put(XxplHeaderRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ACTIVEYN = AttributesEnum.ActiveYn.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTECATEGORY = AttributesEnum.AttributeCategory.index();
    public static final int BUILDID = AttributesEnum.BuildId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CURRENCYCODE = AttributesEnum.CurrencyCode.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int FLOWLEVEL = AttributesEnum.FlowLevel.index();
    public static final int FLOWSTATUS = AttributesEnum.FlowStatus.index();
    public static final int FLOWWITH = AttributesEnum.FlowWith.index();
    public static final int FUNCID = AttributesEnum.FuncId.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int OBJECTVERSION = AttributesEnum.ObjectVersion.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int PLID = AttributesEnum.PlId.index();
    public static final int PLNAME = AttributesEnum.PlName.index();
    public static final int PLNAMETL = AttributesEnum.PlNameTl.index();
    public static final int PLNUMBER = AttributesEnum.PlNumber.index();
    public static final int PLTYPE = AttributesEnum.PlType.index();
    public static final int PRIORITY = AttributesEnum.Priority.index();
    public static final int PROPERTYID = AttributesEnum.PropertyId.index();
    public static final int REVISEDBY = AttributesEnum.RevisedBy.index();
    public static final int REVISIONDATE = AttributesEnum.RevisionDate.index();
    public static final int REVISIONNO = AttributesEnum.RevisionNo.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int USAGE = AttributesEnum.Usage.index();
    public static final int USERGRPID = AttributesEnum.UserGrpId.index();
    public static final int PROPERTYIDTRANS = AttributesEnum.PropertyIdTrans.index();
    public static final int ORGTRANSID = AttributesEnum.OrgTransId.index();
    public static final int BUILDINGTRANSID = AttributesEnum.BuildingTransID.index();
    public static final int PLTYPETRANS = AttributesEnum.PltypeTrans.index();
    public static final int XXPLLINEVO = AttributesEnum.XxplLineVO.index();
    public static final int XXSTG_ORGANIZATIONS_ROVO = AttributesEnum.XXSTG_ORGANIZATIONS_ROVO.index();
    public static final int SEARCHPROPERTYFILTERROVO = AttributesEnum.SearchPropertyFilterROVO.index();
    public static final int SERACHBUILDINGFILTERROVO = AttributesEnum.SerachBuildingFilterROVO.index();
    public static final int XXFND_LOOKUP_V_ROVO = AttributesEnum.XXFND_LOOKUP_V_ROVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxplHeaderRowImpl() {
    }

    /**
     * Gets XxplHeaderEO entity object.
     * @return the XxplHeaderEO
     */
    public XxplHeaderEOImpl getXxplHeaderEO() {
        return (XxplHeaderEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for ACTIVE_YN using the alias name ActiveYn.
     * @return the ACTIVE_YN
     */
    public String getActiveYn() {
        return (String) getAttributeInternal(ACTIVEYN);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVE_YN using the alias name ActiveYn.
     * @param value value to set the ACTIVE_YN
     */
    public void setActiveYn(String value) {
        setAttributeInternal(ACTIVEYN, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @return the ATTRIBUTE_CATEGORY
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @param value value to set the ATTRIBUTE_CATEGORY
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for BUILD_ID using the alias name BuildId.
     * @return the BUILD_ID
     */
    public Number getBuildId() {
       
        return (Number)getAttributeInternal(BUILDID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUILD_ID using the alias name BuildId.
     * @param value value to set the BUILD_ID
     */
    public void setBuildId(Number value) {
        setAttributeInternal(BUILDID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CURRENCY_CODE using the alias name CurrencyCode.
     * @return the CURRENCY_CODE
     */
    public String getCurrencyCode() {
        return (String) getAttributeInternal(CURRENCYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENCY_CODE using the alias name CurrencyCode.
     * @param value value to set the CURRENCY_CODE
     */
    public void setCurrencyCode(String value) {
        setAttributeInternal(CURRENCYCODE, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for END_DATE using the alias name EndDate.
     * @return the END_DATE
     */
    public Date getEndDate() {
        return (Date) getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for END_DATE using the alias name EndDate.
     * @param value value to set the END_DATE
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for FLOW_LEVEL using the alias name FlowLevel.
     * @return the FLOW_LEVEL
     */
    public BigDecimal getFlowLevel() {
        return (BigDecimal) getAttributeInternal(FLOWLEVEL);
    }

    /**
     * Sets <code>value</code> as attribute value for FLOW_LEVEL using the alias name FlowLevel.
     * @param value value to set the FLOW_LEVEL
     */
    public void setFlowLevel(BigDecimal value) {
        setAttributeInternal(FLOWLEVEL, value);
    }

    /**
     * Gets the attribute value for FLOW_STATUS using the alias name FlowStatus.
     * @return the FLOW_STATUS
     */
    public String getFlowStatus() {
        return (String) getAttributeInternal(FLOWSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for FLOW_STATUS using the alias name FlowStatus.
     * @param value value to set the FLOW_STATUS
     */
    public void setFlowStatus(String value) {
        setAttributeInternal(FLOWSTATUS, value);
    }

    /**
     * Gets the attribute value for FLOW_WITH using the alias name FlowWith.
     * @return the FLOW_WITH
     */
    public BigDecimal getFlowWith() {
        return (BigDecimal) getAttributeInternal(FLOWWITH);
    }

    /**
     * Sets <code>value</code> as attribute value for FLOW_WITH using the alias name FlowWith.
     * @param value value to set the FLOW_WITH
     */
    public void setFlowWith(BigDecimal value) {
        setAttributeInternal(FLOWWITH, value);
    }

    /**
     * Gets the attribute value for FUNC_ID using the alias name FuncId.
     * @return the FUNC_ID
     */
    public BigDecimal getFuncId() {
        return (BigDecimal) getAttributeInternal(FUNCID);
    }

    /**
     * Sets <code>value</code> as attribute value for FUNC_ID using the alias name FuncId.
     * @param value value to set the FUNC_ID
     */
    public void setFuncId(BigDecimal value) {
        setAttributeInternal(FUNCID, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION using the alias name ObjectVersion.
     * @return the OBJECT_VERSION
     */
    public BigDecimal getObjectVersion() {
        return (BigDecimal) getAttributeInternal(OBJECTVERSION);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION using the alias name ObjectVersion.
     * @param value value to set the OBJECT_VERSION
     */
    public void setObjectVersion(BigDecimal value) {
        setAttributeInternal(OBJECTVERSION, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for PL_ID using the alias name PlId.
     * @return the PL_ID
     */
    public Number getPlId() {
        return (Number)getAttributeInternal(PLID);
    }

    /**
     * Sets <code>value</code> as attribute value for PL_ID using the alias name PlId.
     * @param value value to set the PL_ID
     */
    public void setPlId(Number value) {
        setAttributeInternal(PLID, value);
    }

    /**
     * Gets the attribute value for PL_NAME using the alias name PlName.
     * @return the PL_NAME
     */
    public String getPlName() {
        return (String) getAttributeInternal(PLNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PL_NAME using the alias name PlName.
     * @param value value to set the PL_NAME
     */
    public void setPlName(String value) {
        setAttributeInternal(PLNAME, value);
    }

    /**
     * Gets the attribute value for PL_NAME_TL using the alias name PlNameTl.
     * @return the PL_NAME_TL
     */
    public String getPlNameTl() {
        return (String) getAttributeInternal(PLNAMETL);
    }

    /**
     * Sets <code>value</code> as attribute value for PL_NAME_TL using the alias name PlNameTl.
     * @param value value to set the PL_NAME_TL
     */
    public void setPlNameTl(String value) {
        setAttributeInternal(PLNAMETL, value);
    }

    /**
     * Gets the attribute value for PL_NUMBER using the alias name PlNumber.
     * @return the PL_NUMBER
     */
    public String getPlNumber() {
        return (String) getAttributeInternal(PLNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for PL_NUMBER using the alias name PlNumber.
     * @param value value to set the PL_NUMBER
     */
    public void setPlNumber(String value) {
        setAttributeInternal(PLNUMBER, value);
    }

    /**
     * Gets the attribute value for PL_TYPE using the alias name PlType.
     * @return the PL_TYPE
     */
    public String getPlType() {
        return (String) getAttributeInternal(PLTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for PL_TYPE using the alias name PlType.
     * @param value value to set the PL_TYPE
     */
    public void setPlType(String value) {
        setAttributeInternal(PLTYPE, value);
    }

    /**
     * Gets the attribute value for PRIORITY using the alias name Priority.
     * @return the PRIORITY
     */
    public BigDecimal getPriority() {
        return (BigDecimal) getAttributeInternal(PRIORITY);
    }

    /**
     * Sets <code>value</code> as attribute value for PRIORITY using the alias name Priority.
     * @param value value to set the PRIORITY
     */
    public void setPriority(BigDecimal value) {
        setAttributeInternal(PRIORITY, value);
    }

    /**
     * Gets the attribute value for PROPERTY_ID using the alias name PropertyId.
     * @return the PROPERTY_ID
     */
    public Number getPropertyId() {
        return (Number)getAttributeInternal(PROPERTYID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROPERTY_ID using the alias name PropertyId.
     * @param value value to set the PROPERTY_ID
     */
    public void setPropertyId(Number value) {
        setAttributeInternal(PROPERTYID, value);
    }

    /**
     * Gets the attribute value for REVISED_BY using the alias name RevisedBy.
     * @return the REVISED_BY
     */
    public String getRevisedBy() {
        return (String) getAttributeInternal(REVISEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for REVISED_BY using the alias name RevisedBy.
     * @param value value to set the REVISED_BY
     */
    public void setRevisedBy(String value) {
        setAttributeInternal(REVISEDBY, value);
    }

    /**
     * Gets the attribute value for REVISION_DATE using the alias name RevisionDate.
     * @return the REVISION_DATE
     */
    public Date getRevisionDate() {
        return (Date) getAttributeInternal(REVISIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for REVISION_DATE using the alias name RevisionDate.
     * @param value value to set the REVISION_DATE
     */
    public void setRevisionDate(Date value) {
        setAttributeInternal(REVISIONDATE, value);
    }

    /**
     * Gets the attribute value for REVISION_NO using the alias name RevisionNo.
     * @return the REVISION_NO
     */
    public BigDecimal getRevisionNo() {
        return (BigDecimal) getAttributeInternal(REVISIONNO);
    }

    /**
     * Sets <code>value</code> as attribute value for REVISION_NO using the alias name RevisionNo.
     * @param value value to set the REVISION_NO
     */
    public void setRevisionNo(BigDecimal value) {
        setAttributeInternal(REVISIONNO, value);
    }

    /**
     * Gets the attribute value for START_DATE using the alias name StartDate.
     * @return the START_DATE
     */
    public Date getStartDate() {
        return (Date) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for START_DATE using the alias name StartDate.
     * @param value value to set the START_DATE
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for USAGE using the alias name Usage.
     * @return the USAGE
     */
    public String getUsage() {
        return (String) getAttributeInternal(USAGE);
    }

    /**
     * Sets <code>value</code> as attribute value for USAGE using the alias name Usage.
     * @param value value to set the USAGE
     */
    public void setUsage(String value) {
        setAttributeInternal(USAGE, value);
    }

    /**
     * Gets the attribute value for USER_GRP_ID using the alias name UserGrpId.
     * @return the USER_GRP_ID
     */
    public BigDecimal getUserGrpId() {
        return (BigDecimal) getAttributeInternal(USERGRPID);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_GRP_ID using the alias name UserGrpId.
     * @param value value to set the USER_GRP_ID
     */
    public void setUserGrpId(BigDecimal value) {
        setAttributeInternal(USERGRPID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PropertyIdTrans.
     * @return the PropertyIdTrans
     */
    public String getPropertyIdTrans() {
        Number buId = null;
                      String departmentName = null;
                      if (getPropertyId() != null) {
                          buId = getPropertyId();
                          Row[] deptRows;
                          deptRows = getSearchPropertyFilterROVO().getFilteredRows("PropertyId", buId);
                          if (deptRows.length > 0) {
                            
                              departmentName =
                                      deptRows[0].getAttribute("PropertyName").toString();
                          }
                              return departmentName;
                          }
                          else {
                              return (String) getAttributeInternal(PROPERTYIDTRANS); 
                          }
                        
        
    
    }
    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PropertyIdTrans.
     * @param value value to set the  PropertyIdTrans
     */
    public void setPropertyIdTrans(String value) {
        setAttributeInternal(PROPERTYIDTRANS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrgTransId.
     * @return the OrgTransId
     */
    public String getOrgTransId() {
        Number buId = null;
                      String departmentName = null;
                      if (getOrgId() != null) {
                          buId = getOrgId();
                          Row[] deptRows;
                          deptRows = getXXSTG_ORGANIZATIONS_ROVO().getFilteredRows("OrgId", buId);
                          if (deptRows.length > 0) {
                              departmentName =
                                      deptRows[0].getAttribute("OrgName").toString();
                          }
                          return departmentName;
                      }
                          else {
                              return (String) getAttributeInternal(ORGTRANSID);
                          }
     
    }
    
    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrgTransId.
     * @param value value to set the  OrgTransId
     */
    public void setOrgTransId(String value) {
        setAttributeInternal(ORGTRANSID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuildingTransID.
     * @return the BuildingTransID
     */
    public String getBuildingTransID() {
        
        Number buId = null;
                      String departmentName = null;
                      if (getBuildId()!= null) {
                          buId = getBuildId();
                          Row[] deptRows;
                          deptRows = getSerachBuildingFilterROVO().getFilteredRows("BuildId", buId);
                          if (deptRows.length > 0) {
                              departmentName =
                                      deptRows[0].getAttribute("BuildName").toString();
                          }
                          return departmentName;
                      }
                          else {
                              return (String) getAttributeInternal(BUILDINGTRANSID);
                          }
      
    }
    
    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuildingTransID.
     * @param value value to set the  BuildingTransID
     */
    public void setBuildingTransID(String value) {
        setAttributeInternal(BUILDINGTRANSID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PltypeTrans.
     * @return the PltypeTrans
     */
    public String getPltypeTrans() {
        String buId=null;
                       String departmentName = null;
                       if (getPlType()!= null) {
                           buId = getPlType();
                           Row[] deptRows;
                           deptRows = getXXFND_LOOKUP_V_ROVO().getFilteredRows("LookupTypeName", buId);
                           if (deptRows.length > 0) {
                               departmentName =
                                       deptRows[0].getAttribute("LookupTypeNameDisp").toString();
                           }
                           return departmentName;
                       }
                       else {
                           return (String) getAttributeInternal(PLTYPETRANS);
                       }
       
    }


    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PltypeTrans.
     * @param value value to set the  PltypeTrans
     */
    public void setPltypeTrans(String value) {
        setAttributeInternal(PLTYPETRANS, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XxplLineVO.
     */
    public RowIterator getXxplLineVO() {
        return (RowIterator)getAttributeInternal(XXPLLINEVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XXSTG_ORGANIZATIONS_ROVO.
     */
    public RowSet getXXSTG_ORGANIZATIONS_ROVO() {
        return (RowSet)getAttributeInternal(XXSTG_ORGANIZATIONS_ROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SearchPropertyFilterROVO.
     */
    public RowSet getSearchPropertyFilterROVO() {
        return (RowSet)getAttributeInternal(SEARCHPROPERTYFILTERROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SerachBuildingFilterROVO.
     */
    public RowSet getSerachBuildingFilterROVO() {
        return (RowSet)getAttributeInternal(SERACHBUILDINGFILTERROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XXFND_LOOKUP_V_ROVO.
     */
    public RowSet getXXFND_LOOKUP_V_ROVO() {
        return (RowSet)getAttributeInternal(XXFND_LOOKUP_V_ROVO);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
