package custom.lease.model.View;

import custom.lease.model.Entity.XxplInvoiceLinesImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 22 16:17:44 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxplInvoiceLineVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Activeyn {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getActiveyn();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setActiveyn((String)value);
            }
        }
        ,
        Amount {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getAmount();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setAmount((BigDecimal)value);
            }
        }
        ,
        Attribute1 {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        AttributeCategory {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getAttributeCategory();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setAttributeCategory((String)value);
            }
        }
        ,
        BookingDtlId {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getBookingDtlId();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setBookingDtlId((BigDecimal)value);
            }
        }
        ,
        BookingMsDtlId {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getBookingMsDtlId();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setBookingMsDtlId((BigDecimal)value);
            }
        }
        ,
        BuildId {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getBuildId();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setBuildId((BigDecimal)value);
            }
        }
        ,
        BuildNumber {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getBuildNumber();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setBuildNumber((String)value);
            }
        }
        ,
        ChargeType {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getChargeType();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setChargeType((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setCreationDate((Timestamp)value);
            }
        }
        ,
        CustomerTrxLineId {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getCustomerTrxLineId();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setCustomerTrxLineId((BigDecimal)value);
            }
        }
        ,
        Description {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getDescription();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        InstallmentType {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getInstallmentType();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setInstallmentType((String)value);
            }
        }
        ,
        InvoiceId {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getInvoiceId();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setInvoiceId((BigDecimal)value);
            }
        }
        ,
        InvoiceLineId {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getInvoiceLineId();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setInvoiceLineId((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setLastUpdateDate((Timestamp)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setLastUpdateLogin((String)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LineAmount {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getLineAmount();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setLineAmount((BigDecimal)value);
            }
        }
        ,
        LineNumber {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getLineNumber();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setLineNumber((BigDecimal)value);
            }
        }
        ,
        LineType {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getLineType();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setLineType((String)value);
            }
        }
        ,
        ObjectVersion {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getObjectVersion();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setObjectVersion((BigDecimal)value);
            }
        }
        ,
        OfferDtlId {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getOfferDtlId();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setOfferDtlId((BigDecimal)value);
            }
        }
        ,
        Price {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getPrice();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setPrice((BigDecimal)value);
            }
        }
        ,
        PropertyId {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getPropertyId();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setPropertyId((BigDecimal)value);
            }
        }
        ,
        PropertyNumber {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getPropertyNumber();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setPropertyNumber((String)value);
            }
        }
        ,
        Quantity {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getQuantity();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setQuantity((BigDecimal)value);
            }
        }
        ,
        RevAcntCode {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getRevAcntCode();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setRevAcntCode((String)value);
            }
        }
        ,
        RevAcntId {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getRevAcntId();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setRevAcntId((BigDecimal)value);
            }
        }
        ,
        TaxAmount {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getTaxAmount();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setTaxAmount((BigDecimal)value);
            }
        }
        ,
        TaxCode {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getTaxCode();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setTaxCode((String)value);
            }
        }
        ,
        TaxPerc {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getTaxPerc();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setTaxPerc((BigDecimal)value);
            }
        }
        ,
        UnitId {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getUnitId();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setUnitId((BigDecimal)value);
            }
        }
        ,
        UnitNumber {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getUnitNumber();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setUnitNumber((String)value);
            }
        }
        ,
        UomCode {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getUomCode();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setUomCode((String)value);
            }
        }
        ,
        Org_id {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getOrg_id();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setOrg_id((Number)value);
            }
        }
        ,
        PropertyTrans {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getPropertyTrans();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setPropertyTrans((String)value);
            }
        }
        ,
        BuildNumberTrans {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getBuildNumberTrans();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setBuildNumberTrans((String)value);
            }
        }
        ,
        CheckBoxFreeze {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getCheckBoxFreeze();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setCheckBoxFreeze((String)value);
            }
        }
        ,
        XxplInvoiceHeader11 {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getXxplInvoiceHeader11();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BookingROVOLOV {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getBookingROVOLOV();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        InvoiceLinesROVO {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getInvoiceLinesROVO();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        XXFND_LOOKUP_V_ROVO {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getXXFND_LOOKUP_V_ROVO();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        XXFND_LOOKUP_V_ROVO_Charge {
            public Object get(XxplInvoiceLineVORowImpl obj) {
                return obj.getXXFND_LOOKUP_V_ROVO_Charge();
            }

            public void put(XxplInvoiceLineVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(XxplInvoiceLineVORowImpl object);

        public abstract void put(XxplInvoiceLineVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ACTIVEYN = AttributesEnum.Activeyn.index();
    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTECATEGORY = AttributesEnum.AttributeCategory.index();
    public static final int BOOKINGDTLID = AttributesEnum.BookingDtlId.index();
    public static final int BOOKINGMSDTLID = AttributesEnum.BookingMsDtlId.index();
    public static final int BUILDID = AttributesEnum.BuildId.index();
    public static final int BUILDNUMBER = AttributesEnum.BuildNumber.index();
    public static final int CHARGETYPE = AttributesEnum.ChargeType.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CUSTOMERTRXLINEID = AttributesEnum.CustomerTrxLineId.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int INSTALLMENTTYPE = AttributesEnum.InstallmentType.index();
    public static final int INVOICEID = AttributesEnum.InvoiceId.index();
    public static final int INVOICELINEID = AttributesEnum.InvoiceLineId.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LINEAMOUNT = AttributesEnum.LineAmount.index();
    public static final int LINENUMBER = AttributesEnum.LineNumber.index();
    public static final int LINETYPE = AttributesEnum.LineType.index();
    public static final int OBJECTVERSION = AttributesEnum.ObjectVersion.index();
    public static final int OFFERDTLID = AttributesEnum.OfferDtlId.index();
    public static final int PRICE = AttributesEnum.Price.index();
    public static final int PROPERTYID = AttributesEnum.PropertyId.index();
    public static final int PROPERTYNUMBER = AttributesEnum.PropertyNumber.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int REVACNTCODE = AttributesEnum.RevAcntCode.index();
    public static final int REVACNTID = AttributesEnum.RevAcntId.index();
    public static final int TAXAMOUNT = AttributesEnum.TaxAmount.index();
    public static final int TAXCODE = AttributesEnum.TaxCode.index();
    public static final int TAXPERC = AttributesEnum.TaxPerc.index();
    public static final int UNITID = AttributesEnum.UnitId.index();
    public static final int UNITNUMBER = AttributesEnum.UnitNumber.index();
    public static final int UOMCODE = AttributesEnum.UomCode.index();
    public static final int ORG_ID = AttributesEnum.Org_id.index();
    public static final int PROPERTYTRANS = AttributesEnum.PropertyTrans.index();
    public static final int BUILDNUMBERTRANS = AttributesEnum.BuildNumberTrans.index();
    public static final int CHECKBOXFREEZE = AttributesEnum.CheckBoxFreeze.index();
    public static final int XXPLINVOICEHEADER11 = AttributesEnum.XxplInvoiceHeader11.index();
    public static final int BOOKINGROVOLOV = AttributesEnum.BookingROVOLOV.index();
    public static final int INVOICELINESROVO = AttributesEnum.InvoiceLinesROVO.index();
    public static final int XXFND_LOOKUP_V_ROVO = AttributesEnum.XXFND_LOOKUP_V_ROVO.index();
    public static final int XXFND_LOOKUP_V_ROVO_CHARGE = AttributesEnum.XXFND_LOOKUP_V_ROVO_Charge.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxplInvoiceLineVORowImpl() {
    }

    /**
     * Gets XxplInvoiceLines entity object.
     * @return the XxplInvoiceLines
     */
    public XxplInvoiceLinesImpl getXxplInvoiceLines() {
        return (XxplInvoiceLinesImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for ACTIVEYN using the alias name Activeyn.
     * @return the ACTIVEYN
     */
    public String getActiveyn() {
        return (String) getAttributeInternal(ACTIVEYN);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVEYN using the alias name Activeyn.
     * @param value value to set the ACTIVEYN
     */
    public void setActiveyn(String value) {
        setAttributeInternal(ACTIVEYN, value);
    }

    /**
     * Gets the attribute value for AMOUNT using the alias name Amount.
     * @return the AMOUNT
     */
    public BigDecimal getAmount() {
        return (BigDecimal) getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for AMOUNT using the alias name Amount.
     * @param value value to set the AMOUNT
     */
    public void setAmount(BigDecimal value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @return the ATTRIBUTE_CATEGORY
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @param value value to set the ATTRIBUTE_CATEGORY
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for BOOKING_DTL_ID using the alias name BookingDtlId.
     * @return the BOOKING_DTL_ID
     */
    public BigDecimal getBookingDtlId() {
        return (BigDecimal) getAttributeInternal(BOOKINGDTLID);
    }

    /**
     * Sets <code>value</code> as attribute value for BOOKING_DTL_ID using the alias name BookingDtlId.
     * @param value value to set the BOOKING_DTL_ID
     */
    public void setBookingDtlId(BigDecimal value) {
        setAttributeInternal(BOOKINGDTLID, value);
    }

    /**
     * Gets the attribute value for BOOKING_MS_DTL_ID using the alias name BookingMsDtlId.
     * @return the BOOKING_MS_DTL_ID
     */
    public BigDecimal getBookingMsDtlId() {
        return (BigDecimal) getAttributeInternal(BOOKINGMSDTLID);
    }

    /**
     * Sets <code>value</code> as attribute value for BOOKING_MS_DTL_ID using the alias name BookingMsDtlId.
     * @param value value to set the BOOKING_MS_DTL_ID
     */
    public void setBookingMsDtlId(BigDecimal value) {
        setAttributeInternal(BOOKINGMSDTLID, value);
    }

    /**
     * Gets the attribute value for BUILD_ID using the alias name BuildId.
     * @return the BUILD_ID
     */
    public BigDecimal getBuildId() {
        return (BigDecimal) getAttributeInternal(BUILDID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUILD_ID using the alias name BuildId.
     * @param value value to set the BUILD_ID
     */
    public void setBuildId(BigDecimal value) {
        setAttributeInternal(BUILDID, value);
    }

    /**
     * Gets the attribute value for BUILD_NUMBER using the alias name BuildNumber.
     * @return the BUILD_NUMBER
     */
    public String getBuildNumber() {
        return (String) getAttributeInternal(BUILDNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for BUILD_NUMBER using the alias name BuildNumber.
     * @param value value to set the BUILD_NUMBER
     */
    public void setBuildNumber(String value) {
        setAttributeInternal(BUILDNUMBER, value);
    }

    /**
     * Gets the attribute value for CHARGE_TYPE using the alias name ChargeType.
     * @return the CHARGE_TYPE
     */
    public String getChargeType() {
        return (String) getAttributeInternal(CHARGETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for CHARGE_TYPE using the alias name ChargeType.
     * @param value value to set the CHARGE_TYPE
     */
    public void setChargeType(String value) {
        setAttributeInternal(CHARGETYPE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_TRX_LINE_ID using the alias name CustomerTrxLineId.
     * @return the CUSTOMER_TRX_LINE_ID
     */
    public BigDecimal getCustomerTrxLineId() {
        return (BigDecimal) getAttributeInternal(CUSTOMERTRXLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_TRX_LINE_ID using the alias name CustomerTrxLineId.
     * @param value value to set the CUSTOMER_TRX_LINE_ID
     */
    public void setCustomerTrxLineId(BigDecimal value) {
        setAttributeInternal(CUSTOMERTRXLINEID, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for INSTALLMENT_TYPE using the alias name InstallmentType.
     * @return the INSTALLMENT_TYPE
     */
    public String getInstallmentType() {
        return (String) getAttributeInternal(INSTALLMENTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for INSTALLMENT_TYPE using the alias name InstallmentType.
     * @param value value to set the INSTALLMENT_TYPE
     */
    public void setInstallmentType(String value) {
        setAttributeInternal(INSTALLMENTTYPE, value);
    }

    /**
     * Gets the attribute value for INVOICE_ID using the alias name InvoiceId.
     * @return the INVOICE_ID
     */
    public BigDecimal getInvoiceId() {
        return (BigDecimal) getAttributeInternal(INVOICEID);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICE_ID using the alias name InvoiceId.
     * @param value value to set the INVOICE_ID
     */
    public void setInvoiceId(BigDecimal value) {
        setAttributeInternal(INVOICEID, value);
    }

    /**
     * Gets the attribute value for INVOICE_LINE_ID using the alias name InvoiceLineId.
     * @return the INVOICE_LINE_ID
     */
    public Number getInvoiceLineId() {
        return (Number)getAttributeInternal(INVOICELINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICE_LINE_ID using the alias name InvoiceLineId.
     * @param value value to set the INVOICE_LINE_ID
     */
    public void setInvoiceLineId(Number value) {
        setAttributeInternal(INVOICELINEID, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LINE_AMOUNT using the alias name LineAmount.
     * @return the LINE_AMOUNT
     */
    public BigDecimal getLineAmount() {
        return (BigDecimal) getAttributeInternal(LINEAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_AMOUNT using the alias name LineAmount.
     * @param value value to set the LINE_AMOUNT
     */
    public void setLineAmount(BigDecimal value) {
        setAttributeInternal(LINEAMOUNT, value);
    }

    /**
     * Gets the attribute value for LINE_NUMBER using the alias name LineNumber.
     * @return the LINE_NUMBER
     */
    public BigDecimal getLineNumber() {
        return (BigDecimal) getAttributeInternal(LINENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_NUMBER using the alias name LineNumber.
     * @param value value to set the LINE_NUMBER
     */
    public void setLineNumber(BigDecimal value) {
        setAttributeInternal(LINENUMBER, value);
    }

    /**
     * Gets the attribute value for LINE_TYPE using the alias name LineType.
     * @return the LINE_TYPE
     */
    public String getLineType() {
        return (String) getAttributeInternal(LINETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_TYPE using the alias name LineType.
     * @param value value to set the LINE_TYPE
     */
    public void setLineType(String value) {
        setAttributeInternal(LINETYPE, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION using the alias name ObjectVersion.
     * @return the OBJECT_VERSION
     */
    public BigDecimal getObjectVersion() {
        return (BigDecimal) getAttributeInternal(OBJECTVERSION);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION using the alias name ObjectVersion.
     * @param value value to set the OBJECT_VERSION
     */
    public void setObjectVersion(BigDecimal value) {
        setAttributeInternal(OBJECTVERSION, value);
    }

    /**
     * Gets the attribute value for OFFER_DTL_ID using the alias name OfferDtlId.
     * @return the OFFER_DTL_ID
     */
    public BigDecimal getOfferDtlId() {
        return (BigDecimal) getAttributeInternal(OFFERDTLID);
    }

    /**
     * Sets <code>value</code> as attribute value for OFFER_DTL_ID using the alias name OfferDtlId.
     * @param value value to set the OFFER_DTL_ID
     */
    public void setOfferDtlId(BigDecimal value) {
        setAttributeInternal(OFFERDTLID, value);
    }

    /**
     * Gets the attribute value for PRICE using the alias name Price.
     * @return the PRICE
     */
    public BigDecimal getPrice() {
        return (BigDecimal) getAttributeInternal(PRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for PRICE using the alias name Price.
     * @param value value to set the PRICE
     */
    public void setPrice(BigDecimal value) {
        setAttributeInternal(PRICE, value);
    }

    /**
     * Gets the attribute value for PROPERTY_ID using the alias name PropertyId.
     * @return the PROPERTY_ID
     */
    public BigDecimal getPropertyId() {
        return (BigDecimal) getAttributeInternal(PROPERTYID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROPERTY_ID using the alias name PropertyId.
     * @param value value to set the PROPERTY_ID
     */
    public void setPropertyId(BigDecimal value) {
        setAttributeInternal(PROPERTYID, value);
    }

    /**
     * Gets the attribute value for PROPERTY_NUMBER using the alias name PropertyNumber.
     * @return the PROPERTY_NUMBER
     */
    public String getPropertyNumber() {
        return (String) getAttributeInternal(PROPERTYNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for PROPERTY_NUMBER using the alias name PropertyNumber.
     * @param value value to set the PROPERTY_NUMBER
     */
    public void setPropertyNumber(String value) {
        setAttributeInternal(PROPERTYNUMBER, value);
    }

    /**
     * Gets the attribute value for QUANTITY using the alias name Quantity.
     * @return the QUANTITY
     */
    public BigDecimal getQuantity() {
        return (BigDecimal) getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for QUANTITY using the alias name Quantity.
     * @param value value to set the QUANTITY
     */
    public void setQuantity(BigDecimal value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for REV_ACNT_CODE using the alias name RevAcntCode.
     * @return the REV_ACNT_CODE
     */
    public String getRevAcntCode() {
        return (String) getAttributeInternal(REVACNTCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for REV_ACNT_CODE using the alias name RevAcntCode.
     * @param value value to set the REV_ACNT_CODE
     */
    public void setRevAcntCode(String value) {
        setAttributeInternal(REVACNTCODE, value);
    }

    /**
     * Gets the attribute value for REV_ACNT_ID using the alias name RevAcntId.
     * @return the REV_ACNT_ID
     */
    public BigDecimal getRevAcntId() {
        return (BigDecimal) getAttributeInternal(REVACNTID);
    }

    /**
     * Sets <code>value</code> as attribute value for REV_ACNT_ID using the alias name RevAcntId.
     * @param value value to set the REV_ACNT_ID
     */
    public void setRevAcntId(BigDecimal value) {
        setAttributeInternal(REVACNTID, value);
    }

    /**
     * Gets the attribute value for TAX_AMOUNT using the alias name TaxAmount.
     * @return the TAX_AMOUNT
     */
    public BigDecimal getTaxAmount() {
        return (BigDecimal) getAttributeInternal(TAXAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_AMOUNT using the alias name TaxAmount.
     * @param value value to set the TAX_AMOUNT
     */
    public void setTaxAmount(BigDecimal value) {
        setAttributeInternal(TAXAMOUNT, value);
    }

    /**
     * Gets the attribute value for TAX_CODE using the alias name TaxCode.
     * @return the TAX_CODE
     */
    public String getTaxCode() {
        return (String) getAttributeInternal(TAXCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_CODE using the alias name TaxCode.
     * @param value value to set the TAX_CODE
     */
    public void setTaxCode(String value) {
        setAttributeInternal(TAXCODE, value);
    }

    /**
     * Gets the attribute value for TAX_PERC using the alias name TaxPerc.
     * @return the TAX_PERC
     */
    public BigDecimal getTaxPerc() {
        return (BigDecimal) getAttributeInternal(TAXPERC);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_PERC using the alias name TaxPerc.
     * @param value value to set the TAX_PERC
     */
    public void setTaxPerc(BigDecimal value) {
        setAttributeInternal(TAXPERC, value);
    }

    /**
     * Gets the attribute value for UNIT_ID using the alias name UnitId.
     * @return the UNIT_ID
     */
    public BigDecimal getUnitId() {
        return (BigDecimal) getAttributeInternal(UNITID);
    }

    /**
     * Sets <code>value</code> as attribute value for UNIT_ID using the alias name UnitId.
     * @param value value to set the UNIT_ID
     */
    public void setUnitId(BigDecimal value) {
        setAttributeInternal(UNITID, value);
    }

    /**
     * Gets the attribute value for UNIT_NUMBER using the alias name UnitNumber.
     * @return the UNIT_NUMBER
     */
    public String getUnitNumber() {
        return (String) getAttributeInternal(UNITNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for UNIT_NUMBER using the alias name UnitNumber.
     * @param value value to set the UNIT_NUMBER
     */
    public void setUnitNumber(String value) {
        setAttributeInternal(UNITNUMBER, value);
    }

    /**
     * Gets the attribute value for UOM_CODE using the alias name UomCode.
     * @return the UOM_CODE
     */
    public String getUomCode() {
        return (String) getAttributeInternal(UOMCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for UOM_CODE using the alias name UomCode.
     * @param value value to set the UOM_CODE
     */
    public void setUomCode(String value) {
        setAttributeInternal(UOMCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Org_id.
     * @return the Org_id
     */
    public Number getOrg_id() {
        return (Number)getAttributeInternal(ORG_ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Org_id.
     * @param value value to set the  Org_id
     */
    public void setOrg_id(Number value) {
        setAttributeInternal(ORG_ID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PropertyTrans.
     * @return the PropertyTrans
     */
    public String getPropertyTrans() {
        BigDecimal buId = null;
        String departmentName = null;
        if (getPropertyId() != null) {
            buId = getPropertyId();
            Row[] deptRows;
            deptRows =
                    getInvoiceLinesROVO().getFilteredRows("PropertyId", buId);
            if (deptRows.length > 0) {
                departmentName =
                        deptRows[0].getAttribute("PropertyName").toString(); //PropertyName
            }
            return departmentName;
        } else {
            return (String)getAttributeInternal(PROPERTYTRANS);
        }

    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PropertyTrans.
     * @param value value to set the  PropertyTrans
     */
    public void setPropertyTrans(String value) {
        setAttributeInternal(PROPERTYTRANS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuildNumberTrans.
     * @return the BuildNumberTrans
     */
    public String getBuildNumberTrans() {
        BigDecimal buId = null;
        String departmentName = null;
        if (getBuildId() != null) {
            buId = getBuildId();
            Row[] deptRows;
            deptRows =
                    getInvoiceLinesROVO().getFilteredRows("BuildingId", buId);
            if (deptRows.length > 0) {
                departmentName =
                        deptRows[0].getAttribute("BuildName").toString();
            }
            return departmentName;
        } else {
            return (String)getAttributeInternal(BUILDNUMBERTRANS);
        }

    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuildNumberTrans.
     * @param value value to set the  BuildNumberTrans
     */
    public void setBuildNumberTrans(String value) {
        setAttributeInternal(BUILDNUMBERTRANS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CheckBoxFreeze.
     * @return the CheckBoxFreeze
     */
    public String getCheckBoxFreeze() {
        return (String) getAttributeInternal(CHECKBOXFREEZE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CheckBoxFreeze.
     * @param value value to set the  CheckBoxFreeze
     */
    public void setCheckBoxFreeze(String value) {
        setAttributeInternal(CHECKBOXFREEZE, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link XxplInvoiceHeader11.
     */
    public Row getXxplInvoiceHeader11() {
        return (Row)getAttributeInternal(XXPLINVOICEHEADER11);
    }

    /**
     * Sets the master-detail link XxplInvoiceHeader11 between this object and <code>value</code>.
     */
    public void setXxplInvoiceHeader11(Row value) {
        setAttributeInternal(XXPLINVOICEHEADER11, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BookingROVOLOV.
     */
    public RowSet getBookingROVOLOV() {
        return (RowSet)getAttributeInternal(BOOKINGROVOLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> InvoiceLinesROVO.
     */
    public RowSet getInvoiceLinesROVO() {
        return (RowSet)getAttributeInternal(INVOICELINESROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XXFND_LOOKUP_V_ROVO.
     */
    public RowSet getXXFND_LOOKUP_V_ROVO() {
        return (RowSet)getAttributeInternal(XXFND_LOOKUP_V_ROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XXFND_LOOKUP_V_ROVO_Charge.
     */
    public RowSet getXXFND_LOOKUP_V_ROVO_Charge() {
        return (RowSet)getAttributeInternal(XXFND_LOOKUP_V_ROVO_CHARGE);
    }


    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
