package custom.lease.model.View;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 01 16:45:19 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxplCancellation_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XxplCancellation_VOImpl() {
    }

    /**
     * Returns the variable value for BV_CANCEL_ID.
     * @return variable value for BV_CANCEL_ID
     */
    public Number getBV_CANCEL_ID() {
        return (Number)ensureVariableManager().getVariableValue("BV_CANCEL_ID");
    }

    /**
     * Sets <code>value</code> for variable BV_CANCEL_ID.
     * @param value value to bind as BV_CANCEL_ID
     */
    public void setBV_CANCEL_ID(Number value) {
        ensureVariableManager().setVariableValue("BV_CANCEL_ID", value);
    }
}
