package custom.lease.model.Entity;

import java.math.BigDecimal;

import java.sql.Clob;
import java.sql.Date;
import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowInconsistentException;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 05 16:19:05 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxplCancellation_EOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CancelId {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getCancelId();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setCancelId((Number)value);
            }
        }
        ,
        FuncId {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getFuncId();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setFuncId((BigDecimal)value);
            }
        }
        ,
        LeaseAgreementId {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getLeaseAgreementId();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setLeaseAgreementId((BigDecimal)value);
            }
        }
        ,
        BookingId {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getBookingId();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setBookingId((Number)value);
            }
        }
        ,
        CancelType {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getCancelType();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setCancelType((String)value);
            }
        }
        ,
        CancelNumber {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getCancelNumber();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setCancelNumber((String)value);
            }
        }
        ,
        CancelDate {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getCancelDate();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setCancelDate((oracle.jbo.domain.Timestamp)value);
            }
        }
        ,
        FinalCancelDate {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getFinalCancelDate();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setFinalCancelDate((Date)value);
            }
        }
        ,
        Currency {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getCurrency();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setCurrency((String)value);
            }
        }
        ,
        RefundAmount {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getRefundAmount();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setRefundAmount((BigDecimal)value);
            }
        }
        ,
        ObjectVersionNumber {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getObjectVersionNumber();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setObjectVersionNumber((BigDecimal)value);
            }
        }
        ,
        DldCancelStatus {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getDldCancelStatus();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setDldCancelStatus((String)value);
            }
        }
        ,
        DldCancelDate {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getDldCancelDate();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setDldCancelDate((Date)value);
            }
        }
        ,
        Status {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getStatus();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        Description {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getDescription();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        OrgId {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getOrgId();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        UserGrpId {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getUserGrpId();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setUserGrpId((BigDecimal)value);
            }
        }
        ,
        FlowStatus {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getFlowStatus();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setFlowStatus((String)value);
            }
        }
        ,
        FlowLevel {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getFlowLevel();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setFlowLevel((BigDecimal)value);
            }
        }
        ,
        FlowWith {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getFlowWith();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setFlowWith((BigDecimal)value);
            }
        }
        ,
        AttributeCategory {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getAttributeCategory();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setAttributeCategory((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getAttribute1();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getAttribute2();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getAttribute3();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getAttribute4();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getAttribute5();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getAttribute6();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getAttribute7();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getAttribute8();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getAttribute9();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getAttribute10();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setCreationDate((oracle.jbo.domain.Timestamp)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setLastUpdateDate((oracle.jbo.domain.Timestamp)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setLastUpdateLogin((String)value);
            }
        }
        ,
        ForfietAmount {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getForfietAmount();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setForfietAmount((BigDecimal)value);
            }
        }
        ,
        AdjustmentAmt {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getAdjustmentAmt();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setAdjustmentAmt((BigDecimal)value);
            }
        }
        ,
        InterfaceStatus {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getInterfaceStatus();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setInterfaceStatus((String)value);
            }
        }
        ,
        InterfaceErrorMsg {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getInterfaceErrorMsg();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setInterfaceErrorMsg((Clob)value);
            }
        }
        ,
        Building {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getBuilding();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setBuilding((BigDecimal)value);
            }
        }
        ,
        ContractValue {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getContractValue();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setContractValue((BigDecimal)value);
            }
        }
        ,
        CustContactId {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getCustContactId();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setCustContactId((BigDecimal)value);
            }
        }
        ,
        CustId {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getCustId();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setCustId((BigDecimal)value);
            }
        }
        ,
        CustSiteId {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getCustSiteId();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setCustSiteId((BigDecimal)value);
            }
        }
        ,
        DailyDiscountRate {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getDailyDiscountRate();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setDailyDiscountRate((BigDecimal)value);
            }
        }
        ,
        DailyRentalRate {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getDailyRentalRate();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setDailyRentalRate((BigDecimal)value);
            }
        }
        ,
        DaysConsumed {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getDaysConsumed();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setDaysConsumed((BigDecimal)value);
            }
        }
        ,
        DaysRemaining {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getDaysRemaining();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setDaysRemaining((BigDecimal)value);
            }
        }
        ,
        Discount {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getDiscount();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setDiscount((BigDecimal)value);
            }
        }
        ,
        NetRent {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getNetRent();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setNetRent((BigDecimal)value);
            }
        }
        ,
        NocBy {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getNocBy();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setNocBy((String)value);
            }
        }
        ,
        NocDateActual {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getNocDateActual();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setNocDateActual((Date)value);
            }
        }
        ,
        NocDateEntered {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getNocDateEntered();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setNocDateEntered((Date)value);
            }
        }
        ,
        PropertyId {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getPropertyId();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setPropertyId((BigDecimal)value);
            }
        }
        ,
        SecurityDepositAmt {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getSecurityDepositAmt();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setSecurityDepositAmt((BigDecimal)value);
            }
        }
        ,
        TaxCode {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getTaxCode();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setTaxCode((String)value);
            }
        }
        ,
        TaxRate {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getTaxRate();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setTaxRate((BigDecimal)value);
            }
        }
        ,
        CmcAmountTotal {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getCmcAmountTotal();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setCmcAmountTotal((BigDecimal)value);
            }
        }
        ,
        CmcErrorMessage {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getCmcErrorMessage();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setCmcErrorMessage((String)value);
            }
        }
        ,
        CmcIntegrationStaus {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getCmcIntegrationStaus();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setCmcIntegrationStaus((String)value);
            }
        }
        ,
        CmcInvoiceNumber {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getCmcInvoiceNumber();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setCmcInvoiceNumber((String)value);
            }
        }
        ,
        XxplBookingMilestones_EO {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getXxplBookingMilestones_EO();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        XxplCancellationDtl_EO {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getXxplCancellationDtl_EO();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        XxplCancellationCharge_EO {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getXxplCancellationCharge_EO();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        XxplBookingMilestones_EO1 {
            public Object get(XxplCancellation_EOImpl obj) {
                return obj.getXxplBookingMilestones_EO1();
            }

            public void put(XxplCancellation_EOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(XxplCancellation_EOImpl object);

        public abstract void put(XxplCancellation_EOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CANCELID = AttributesEnum.CancelId.index();
    public static final int FUNCID = AttributesEnum.FuncId.index();
    public static final int LEASEAGREEMENTID = AttributesEnum.LeaseAgreementId.index();
    public static final int BOOKINGID = AttributesEnum.BookingId.index();
    public static final int CANCELTYPE = AttributesEnum.CancelType.index();
    public static final int CANCELNUMBER = AttributesEnum.CancelNumber.index();
    public static final int CANCELDATE = AttributesEnum.CancelDate.index();
    public static final int FINALCANCELDATE = AttributesEnum.FinalCancelDate.index();
    public static final int CURRENCY = AttributesEnum.Currency.index();
    public static final int REFUNDAMOUNT = AttributesEnum.RefundAmount.index();
    public static final int OBJECTVERSIONNUMBER = AttributesEnum.ObjectVersionNumber.index();
    public static final int DLDCANCELSTATUS = AttributesEnum.DldCancelStatus.index();
    public static final int DLDCANCELDATE = AttributesEnum.DldCancelDate.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int USERGRPID = AttributesEnum.UserGrpId.index();
    public static final int FLOWSTATUS = AttributesEnum.FlowStatus.index();
    public static final int FLOWLEVEL = AttributesEnum.FlowLevel.index();
    public static final int FLOWWITH = AttributesEnum.FlowWith.index();
    public static final int ATTRIBUTECATEGORY = AttributesEnum.AttributeCategory.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int FORFIETAMOUNT = AttributesEnum.ForfietAmount.index();
    public static final int ADJUSTMENTAMT = AttributesEnum.AdjustmentAmt.index();
    public static final int INTERFACESTATUS = AttributesEnum.InterfaceStatus.index();
    public static final int INTERFACEERRORMSG = AttributesEnum.InterfaceErrorMsg.index();
    public static final int BUILDING = AttributesEnum.Building.index();
    public static final int CONTRACTVALUE = AttributesEnum.ContractValue.index();
    public static final int CUSTCONTACTID = AttributesEnum.CustContactId.index();
    public static final int CUSTID = AttributesEnum.CustId.index();
    public static final int CUSTSITEID = AttributesEnum.CustSiteId.index();
    public static final int DAILYDISCOUNTRATE = AttributesEnum.DailyDiscountRate.index();
    public static final int DAILYRENTALRATE = AttributesEnum.DailyRentalRate.index();
    public static final int DAYSCONSUMED = AttributesEnum.DaysConsumed.index();
    public static final int DAYSREMAINING = AttributesEnum.DaysRemaining.index();
    public static final int DISCOUNT = AttributesEnum.Discount.index();
    public static final int NETRENT = AttributesEnum.NetRent.index();
    public static final int NOCBY = AttributesEnum.NocBy.index();
    public static final int NOCDATEACTUAL = AttributesEnum.NocDateActual.index();
    public static final int NOCDATEENTERED = AttributesEnum.NocDateEntered.index();
    public static final int PROPERTYID = AttributesEnum.PropertyId.index();
    public static final int SECURITYDEPOSITAMT = AttributesEnum.SecurityDepositAmt.index();
    public static final int TAXCODE = AttributesEnum.TaxCode.index();
    public static final int TAXRATE = AttributesEnum.TaxRate.index();
    public static final int CMCAMOUNTTOTAL = AttributesEnum.CmcAmountTotal.index();
    public static final int CMCERRORMESSAGE = AttributesEnum.CmcErrorMessage.index();
    public static final int CMCINTEGRATIONSTAUS = AttributesEnum.CmcIntegrationStaus.index();
    public static final int CMCINVOICENUMBER = AttributesEnum.CmcInvoiceNumber.index();
    public static final int XXPLBOOKINGMILESTONES_EO = AttributesEnum.XxplBookingMilestones_EO.index();
    public static final int XXPLCANCELLATIONDTL_EO = AttributesEnum.XxplCancellationDtl_EO.index();
    public static final int XXPLCANCELLATIONCHARGE_EO = AttributesEnum.XxplCancellationCharge_EO.index();
    public static final int XXPLBOOKINGMILESTONES_EO1 = AttributesEnum.XxplBookingMilestones_EO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxplCancellation_EOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("custom.lease.model.Entity.XxplCancellation_EO");
    }

    /**
     * Gets the attribute value for CancelId, using the alias name CancelId.
     * @return the CancelId
     */
    public Number getCancelId() {
        return (Number)getAttributeInternal(CANCELID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CancelId.
     * @param value value to set the CancelId
     */
    public void setCancelId(Number value) {
        setAttributeInternal(CANCELID, value);
    }

    /**
     * Gets the attribute value for FuncId, using the alias name FuncId.
     * @return the FuncId
     */
    public BigDecimal getFuncId() {
        return (BigDecimal)getAttributeInternal(FUNCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FuncId.
     * @param value value to set the FuncId
     */
    public void setFuncId(BigDecimal value) {
        setAttributeInternal(FUNCID, value);
    }

    /**
     * Gets the attribute value for LeaseAgreementId, using the alias name LeaseAgreementId.
     * @return the LeaseAgreementId
     */
    public BigDecimal getLeaseAgreementId() {
        return (BigDecimal)getAttributeInternal(LEASEAGREEMENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LeaseAgreementId.
     * @param value value to set the LeaseAgreementId
     */
    public void setLeaseAgreementId(BigDecimal value) {
        setAttributeInternal(LEASEAGREEMENTID, value);
    }

    /**
     * Gets the attribute value for BookingId, using the alias name BookingId.
     * @return the BookingId
     */
    public Number getBookingId() {
        return (Number)getAttributeInternal(BOOKINGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BookingId.
     * @param value value to set the BookingId
     */
    public void setBookingId(Number value) {
        setAttributeInternal(BOOKINGID, value);
    }

    /**
     * Gets the attribute value for CancelType, using the alias name CancelType.
     * @return the CancelType
     */
    public String getCancelType() {
        return (String)getAttributeInternal(CANCELTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CancelType.
     * @param value value to set the CancelType
     */
    public void setCancelType(String value) {
        setAttributeInternal(CANCELTYPE, value);
    }

    /**
     * Gets the attribute value for CancelNumber, using the alias name CancelNumber.
     * @return the CancelNumber
     */
    public String getCancelNumber() {
        return (String)getAttributeInternal(CANCELNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for CancelNumber.
     * @param value value to set the CancelNumber
     */
    public void setCancelNumber(String value) {
        setAttributeInternal(CANCELNUMBER, value);
    }

    /**
     * Gets the attribute value for CancelDate, using the alias name CancelDate.
     * @return the CancelDate
     */
    public oracle.jbo.domain.Timestamp getCancelDate() {
        return (oracle.jbo.domain.Timestamp)getAttributeInternal(CANCELDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CancelDate.
     * @param value value to set the CancelDate
     */
    public void setCancelDate(oracle.jbo.domain.Timestamp value) {
        setAttributeInternal(CANCELDATE, value);
    }

    /**
     * Gets the attribute value for FinalCancelDate, using the alias name FinalCancelDate.
     * @return the FinalCancelDate
     */
    public Date getFinalCancelDate() {
        return (Date)getAttributeInternal(FINALCANCELDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FinalCancelDate.
     * @param value value to set the FinalCancelDate
     */
    public void setFinalCancelDate(Date value) {
        setAttributeInternal(FINALCANCELDATE, value);
    }

    /**
     * Gets the attribute value for Currency, using the alias name Currency.
     * @return the Currency
     */
    public String getCurrency() {
        return (String)getAttributeInternal(CURRENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Currency.
     * @param value value to set the Currency
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**
     * Gets the attribute value for RefundAmount, using the alias name RefundAmount.
     * @return the RefundAmount
     */
    public BigDecimal getRefundAmount() {
        return (BigDecimal)getAttributeInternal(REFUNDAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for RefundAmount.
     * @param value value to set the RefundAmount
     */
    public void setRefundAmount(BigDecimal value) {
        setAttributeInternal(REFUNDAMOUNT, value);
    }

    /**
     * Gets the attribute value for ObjectVersionNumber, using the alias name ObjectVersionNumber.
     * @return the ObjectVersionNumber
     */
    public BigDecimal getObjectVersionNumber() {
        return (BigDecimal)getAttributeInternal(OBJECTVERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for ObjectVersionNumber.
     * @param value value to set the ObjectVersionNumber
     */
    public void setObjectVersionNumber(BigDecimal value) {
        setAttributeInternal(OBJECTVERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for DldCancelStatus, using the alias name DldCancelStatus.
     * @return the DldCancelStatus
     */
    public String getDldCancelStatus() {
        return (String)getAttributeInternal(DLDCANCELSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for DldCancelStatus.
     * @param value value to set the DldCancelStatus
     */
    public void setDldCancelStatus(String value) {
        setAttributeInternal(DLDCANCELSTATUS, value);
    }

    /**
     * Gets the attribute value for DldCancelDate, using the alias name DldCancelDate.
     * @return the DldCancelDate
     */
    public Date getDldCancelDate() {
        return (Date)getAttributeInternal(DLDCANCELDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DldCancelDate.
     * @param value value to set the DldCancelDate
     */
    public void setDldCancelDate(Date value) {
        setAttributeInternal(DLDCANCELDATE, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the Status
     */
    public String getStatus() {
        return (String)getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for Description, using the alias name Description.
     * @return the Description
     */
    public String getDescription() {
        return (String)getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Description.
     * @param value value to set the Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for UserGrpId, using the alias name UserGrpId.
     * @return the UserGrpId
     */
    public BigDecimal getUserGrpId() {
        return (BigDecimal)getAttributeInternal(USERGRPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserGrpId.
     * @param value value to set the UserGrpId
     */
    public void setUserGrpId(BigDecimal value) {
        setAttributeInternal(USERGRPID, value);
    }

    /**
     * Gets the attribute value for FlowStatus, using the alias name FlowStatus.
     * @return the FlowStatus
     */
    public String getFlowStatus() {
        return (String)getAttributeInternal(FLOWSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for FlowStatus.
     * @param value value to set the FlowStatus
     */
    public void setFlowStatus(String value) {
        setAttributeInternal(FLOWSTATUS, value);
    }

    /**
     * Gets the attribute value for FlowLevel, using the alias name FlowLevel.
     * @return the FlowLevel
     */
    public BigDecimal getFlowLevel() {
        return (BigDecimal)getAttributeInternal(FLOWLEVEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for FlowLevel.
     * @param value value to set the FlowLevel
     */
    public void setFlowLevel(BigDecimal value) {
        setAttributeInternal(FLOWLEVEL, value);
    }

    /**
     * Gets the attribute value for FlowWith, using the alias name FlowWith.
     * @return the FlowWith
     */
    public BigDecimal getFlowWith() {
        return (BigDecimal)getAttributeInternal(FLOWWITH);
    }

    /**
     * Sets <code>value</code> as the attribute value for FlowWith.
     * @param value value to set the FlowWith
     */
    public void setFlowWith(BigDecimal value) {
        setAttributeInternal(FLOWWITH, value);
    }

    /**
     * Gets the attribute value for AttributeCategory, using the alias name AttributeCategory.
     * @return the AttributeCategory
     */
    public String getAttributeCategory() {
        return (String)getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeCategory.
     * @param value value to set the AttributeCategory
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(oracle.jbo.domain.Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(oracle.jbo.domain.Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public String getLastUpdateLogin() {
        return (String)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for ForfietAmount, using the alias name ForfietAmount.
     * @return the ForfietAmount
     */
    public BigDecimal getForfietAmount() {
        return (BigDecimal)getAttributeInternal(FORFIETAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ForfietAmount.
     * @param value value to set the ForfietAmount
     */
    public void setForfietAmount(BigDecimal value) {
        setAttributeInternal(FORFIETAMOUNT, value);
    }

    /**
     * Gets the attribute value for AdjustmentAmt, using the alias name AdjustmentAmt.
     * @return the AdjustmentAmt
     */
    public BigDecimal getAdjustmentAmt() {
        return (BigDecimal)getAttributeInternal(ADJUSTMENTAMT);
    }

    /**
     * Sets <code>value</code> as the attribute value for AdjustmentAmt.
     * @param value value to set the AdjustmentAmt
     */
    public void setAdjustmentAmt(BigDecimal value) {
        setAttributeInternal(ADJUSTMENTAMT, value);
    }

    /**
     * Gets the attribute value for InterfaceStatus, using the alias name InterfaceStatus.
     * @return the InterfaceStatus
     */
    public String getInterfaceStatus() {
        return (String)getAttributeInternal(INTERFACESTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for InterfaceStatus.
     * @param value value to set the InterfaceStatus
     */
    public void setInterfaceStatus(String value) {
        setAttributeInternal(INTERFACESTATUS, value);
    }

    /**
     * Gets the attribute value for InterfaceErrorMsg, using the alias name InterfaceErrorMsg.
     * @return the InterfaceErrorMsg
     */
    public Clob getInterfaceErrorMsg() {
        return (Clob)getAttributeInternal(INTERFACEERRORMSG);
    }

    /**
     * Sets <code>value</code> as the attribute value for InterfaceErrorMsg.
     * @param value value to set the InterfaceErrorMsg
     */
    public void setInterfaceErrorMsg(Clob value) {
        setAttributeInternal(INTERFACEERRORMSG, value);
    }

    /**
     * Gets the attribute value for Building, using the alias name Building.
     * @return the Building
     */
    public BigDecimal getBuilding() {
        return (BigDecimal)getAttributeInternal(BUILDING);
    }

    /**
     * Sets <code>value</code> as the attribute value for Building.
     * @param value value to set the Building
     */
    public void setBuilding(BigDecimal value) {
        setAttributeInternal(BUILDING, value);
    }

    /**
     * Gets the attribute value for ContractValue, using the alias name ContractValue.
     * @return the ContractValue
     */
    public BigDecimal getContractValue() {
        return (BigDecimal)getAttributeInternal(CONTRACTVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContractValue.
     * @param value value to set the ContractValue
     */
    public void setContractValue(BigDecimal value) {
        setAttributeInternal(CONTRACTVALUE, value);
    }

    /**
     * Gets the attribute value for CustContactId, using the alias name CustContactId.
     * @return the CustContactId
     */
    public BigDecimal getCustContactId() {
        return (BigDecimal)getAttributeInternal(CUSTCONTACTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustContactId.
     * @param value value to set the CustContactId
     */
    public void setCustContactId(BigDecimal value) {
        setAttributeInternal(CUSTCONTACTID, value);
    }

    /**
     * Gets the attribute value for CustId, using the alias name CustId.
     * @return the CustId
     */
    public BigDecimal getCustId() {
        return (BigDecimal)getAttributeInternal(CUSTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustId.
     * @param value value to set the CustId
     */
    public void setCustId(BigDecimal value) {
        setAttributeInternal(CUSTID, value);
    }

    /**
     * Gets the attribute value for CustSiteId, using the alias name CustSiteId.
     * @return the CustSiteId
     */
    public BigDecimal getCustSiteId() {
        return (BigDecimal)getAttributeInternal(CUSTSITEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustSiteId.
     * @param value value to set the CustSiteId
     */
    public void setCustSiteId(BigDecimal value) {
        setAttributeInternal(CUSTSITEID, value);
    }

    /**
     * Gets the attribute value for DailyDiscountRate, using the alias name DailyDiscountRate.
     * @return the DailyDiscountRate
     */
    public BigDecimal getDailyDiscountRate() {
        return (BigDecimal)getAttributeInternal(DAILYDISCOUNTRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DailyDiscountRate.
     * @param value value to set the DailyDiscountRate
     */
    public void setDailyDiscountRate(BigDecimal value) {
        setAttributeInternal(DAILYDISCOUNTRATE, value);
    }

    /**
     * Gets the attribute value for DailyRentalRate, using the alias name DailyRentalRate.
     * @return the DailyRentalRate
     */
    public BigDecimal getDailyRentalRate() {
        return (BigDecimal)getAttributeInternal(DAILYRENTALRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DailyRentalRate.
     * @param value value to set the DailyRentalRate
     */
    public void setDailyRentalRate(BigDecimal value) {
        setAttributeInternal(DAILYRENTALRATE, value);
    }

    /**
     * Gets the attribute value for DaysConsumed, using the alias name DaysConsumed.
     * @return the DaysConsumed
     */
    public BigDecimal getDaysConsumed() {
        return (BigDecimal)getAttributeInternal(DAYSCONSUMED);
    }

    /**
     * Sets <code>value</code> as the attribute value for DaysConsumed.
     * @param value value to set the DaysConsumed
     */
    public void setDaysConsumed(BigDecimal value) {
        setAttributeInternal(DAYSCONSUMED, value);
    }

    /**
     * Gets the attribute value for DaysRemaining, using the alias name DaysRemaining.
     * @return the DaysRemaining
     */
    public BigDecimal getDaysRemaining() {
        return (BigDecimal)getAttributeInternal(DAYSREMAINING);
    }

    /**
     * Sets <code>value</code> as the attribute value for DaysRemaining.
     * @param value value to set the DaysRemaining
     */
    public void setDaysRemaining(BigDecimal value) {
        setAttributeInternal(DAYSREMAINING, value);
    }

    /**
     * Gets the attribute value for Discount, using the alias name Discount.
     * @return the Discount
     */
    public BigDecimal getDiscount() {
        return (BigDecimal)getAttributeInternal(DISCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Discount.
     * @param value value to set the Discount
     */
    public void setDiscount(BigDecimal value) {
        setAttributeInternal(DISCOUNT, value);
    }

    /**
     * Gets the attribute value for NetRent, using the alias name NetRent.
     * @return the NetRent
     */
    public BigDecimal getNetRent() {
        return (BigDecimal)getAttributeInternal(NETRENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for NetRent.
     * @param value value to set the NetRent
     */
    public void setNetRent(BigDecimal value) {
        setAttributeInternal(NETRENT, value);
    }

    /**
     * Gets the attribute value for NocBy, using the alias name NocBy.
     * @return the NocBy
     */
    public String getNocBy() {
        return (String)getAttributeInternal(NOCBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for NocBy.
     * @param value value to set the NocBy
     */
    public void setNocBy(String value) {
        setAttributeInternal(NOCBY, value);
    }

    /**
     * Gets the attribute value for NocDateActual, using the alias name NocDateActual.
     * @return the NocDateActual
     */
    public Date getNocDateActual() {
        return (Date)getAttributeInternal(NOCDATEACTUAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for NocDateActual.
     * @param value value to set the NocDateActual
     */
    public void setNocDateActual(Date value) {
        setAttributeInternal(NOCDATEACTUAL, value);
    }

    /**
     * Gets the attribute value for NocDateEntered, using the alias name NocDateEntered.
     * @return the NocDateEntered
     */
    public Date getNocDateEntered() {
        return (Date)getAttributeInternal(NOCDATEENTERED);
    }

    /**
     * Sets <code>value</code> as the attribute value for NocDateEntered.
     * @param value value to set the NocDateEntered
     */
    public void setNocDateEntered(Date value) {
        setAttributeInternal(NOCDATEENTERED, value);
    }

    /**
     * Gets the attribute value for PropertyId, using the alias name PropertyId.
     * @return the PropertyId
     */
    public BigDecimal getPropertyId() {
        return (BigDecimal)getAttributeInternal(PROPERTYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PropertyId.
     * @param value value to set the PropertyId
     */
    public void setPropertyId(BigDecimal value) {
        setAttributeInternal(PROPERTYID, value);
    }

    /**
     * Gets the attribute value for SecurityDepositAmt, using the alias name SecurityDepositAmt.
     * @return the SecurityDepositAmt
     */
    public BigDecimal getSecurityDepositAmt() {
        return (BigDecimal)getAttributeInternal(SECURITYDEPOSITAMT);
    }

    /**
     * Sets <code>value</code> as the attribute value for SecurityDepositAmt.
     * @param value value to set the SecurityDepositAmt
     */
    public void setSecurityDepositAmt(BigDecimal value) {
        setAttributeInternal(SECURITYDEPOSITAMT, value);
    }

    /**
     * Gets the attribute value for TaxCode, using the alias name TaxCode.
     * @return the TaxCode
     */
    public String getTaxCode() {
        return (String)getAttributeInternal(TAXCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TaxCode.
     * @param value value to set the TaxCode
     */
    public void setTaxCode(String value) {
        setAttributeInternal(TAXCODE, value);
    }

    /**
     * Gets the attribute value for TaxRate, using the alias name TaxRate.
     * @return the TaxRate
     */
    public BigDecimal getTaxRate() {
        return (BigDecimal)getAttributeInternal(TAXRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TaxRate.
     * @param value value to set the TaxRate
     */
    public void setTaxRate(BigDecimal value) {
        setAttributeInternal(TAXRATE, value);
    }

    /**
     * Gets the attribute value for CmcAmountTotal, using the alias name CmcAmountTotal.
     * @return the CmcAmountTotal
     */
    public BigDecimal getCmcAmountTotal() {
        return (BigDecimal)getAttributeInternal(CMCAMOUNTTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for CmcAmountTotal.
     * @param value value to set the CmcAmountTotal
     */
    public void setCmcAmountTotal(BigDecimal value) {
        setAttributeInternal(CMCAMOUNTTOTAL, value);
    }

    /**
     * Gets the attribute value for CmcErrorMessage, using the alias name CmcErrorMessage.
     * @return the CmcErrorMessage
     */
    public String getCmcErrorMessage() {
        return (String)getAttributeInternal(CMCERRORMESSAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CmcErrorMessage.
     * @param value value to set the CmcErrorMessage
     */
    public void setCmcErrorMessage(String value) {
        setAttributeInternal(CMCERRORMESSAGE, value);
    }

    /**
     * Gets the attribute value for CmcIntegrationStaus, using the alias name CmcIntegrationStaus.
     * @return the CmcIntegrationStaus
     */
    public String getCmcIntegrationStaus() {
        return (String)getAttributeInternal(CMCINTEGRATIONSTAUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for CmcIntegrationStaus.
     * @param value value to set the CmcIntegrationStaus
     */
    public void setCmcIntegrationStaus(String value) {
        setAttributeInternal(CMCINTEGRATIONSTAUS, value);
    }

    /**
     * Gets the attribute value for CmcInvoiceNumber, using the alias name CmcInvoiceNumber.
     * @return the CmcInvoiceNumber
     */
    public String getCmcInvoiceNumber() {
        return (String)getAttributeInternal(CMCINVOICENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for CmcInvoiceNumber.
     * @param value value to set the CmcInvoiceNumber
     */
    public void setCmcInvoiceNumber(String value) {
        setAttributeInternal(CMCINVOICENUMBER, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getXxplBookingMilestones_EO() {
        return (RowIterator)getAttributeInternal(XXPLBOOKINGMILESTONES_EO);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getXxplCancellationDtl_EO() {
        return (RowIterator)getAttributeInternal(XXPLCANCELLATIONDTL_EO);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getXxplCancellationCharge_EO() {
        return (RowIterator)getAttributeInternal(XXPLCANCELLATIONCHARGE_EO);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getXxplBookingMilestones_EO1() {
        return (RowIterator)getAttributeInternal(XXPLBOOKINGMILESTONES_EO1);
    }


    /**
     * @param cancelId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number cancelId) {
        return new Key(new Object[]{cancelId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        SequenceImpl seq = new SequenceImpl("BOOKING_HDR_ID_S", this.getDBTransaction());
        this.setCancelId(seq.getSequenceNumber());
        this.setCancelDate(new oracle.jbo.domain.Timestamp(System.currentTimeMillis()));
        this.setCreatedBy(ADFContext.getCurrent().getSessionScope().get("userName").toString());
        this.setLastUpdatedBy(ADFContext.getCurrent().getSessionScope().get("userName").toString());
        this.setLastUpdateLogin(ADFContext.getCurrent().getSessionScope().get("userName").toString());
        this.setLastUpdateDate(new oracle.jbo.domain.Timestamp(System.currentTimeMillis()));
        this.setCreationDate(new oracle.jbo.domain.Timestamp(System.currentTimeMillis()));  
        this.setFuncId(new BigDecimal(12));
        this.setStatus("Draft");
        super.create(attributeList);
    }

    /**
     * Add locking logic here.
     */
//    public void lock() {
//        super.lock();
//    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if(operation==EntityImpl.DML_UPDATE){
            this.setLastUpdatedBy(ADFContext.getCurrent().getSessionScope().get("userName").toString());
            this.setLastUpdateLogin(ADFContext.getCurrent().getSessionScope().get("userName").toString());
            this.setLastUpdateDate(new oracle.jbo.domain.Timestamp(System.currentTimeMillis()));
        }
        if(operation==EntityImpl.DML_INSERT){
            String cancelId = this.getCancelId().toString();
            String cancelNo = "CN - "+cancelId; 
            this.setCancelNumber(cancelNo);
        }
        super.doDML(operation, e);
    }
    @Override
   public void lock() {
        try {
            super.lock();
          } catch (RowInconsistentException e) {
            refresh(REFRESH_WITH_DB_ONLY_IF_UNCHANGED | REFRESH_CONTAINEES);
            super.lock();
            }
        }
}
