package custom.lease.model.Entity;

import java.math.BigDecimal;

import java.sql.Clob;
import java.sql.Date;
import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 16 11:21:49 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxplInvoiceHeaderImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        InvoiceId {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getInvoiceId();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setInvoiceId((Number)value);
            }
        }
        ,
        InvoiceNumber {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getInvoiceNumber();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setInvoiceNumber((String)value);
            }
        }
        ,
        InvoiceDate {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getInvoiceDate();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setInvoiceDate((Date)value);
            }
        }
        ,
        FuncId {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getFuncId();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setFuncId((BigDecimal)value);
            }
        }
        ,
        InvoiceClass {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getInvoiceClass();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setInvoiceClass((String)value);
            }
        }
        ,
        OrgId {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getOrgId();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        TrxSource {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getTrxSource();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setTrxSource((String)value);
            }
        }
        ,
        TrxType {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getTrxType();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setTrxType((String)value);
            }
        }
        ,
        CurrencyCode {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getCurrencyCode();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setCurrencyCode((String)value);
            }
        }
        ,
        ExchangeRate {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getExchangeRate();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setExchangeRate((BigDecimal)value);
            }
        }
        ,
        CustId {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getCustId();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setCustId((BigDecimal)value);
            }
        }
        ,
        CustSiteId {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getCustSiteId();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setCustSiteId((BigDecimal)value);
            }
        }
        ,
        DueDate {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getDueDate();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setDueDate((Date)value);
            }
        }
        ,
        Status {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getStatus();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        InterfaceStatus {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getInterfaceStatus();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setInterfaceStatus((String)value);
            }
        }
        ,
        OfferId {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getOfferId();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setOfferId((BigDecimal)value);
            }
        }
        ,
        OfferNumber {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getOfferNumber();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setOfferNumber((String)value);
            }
        }
        ,
        BookingId {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getBookingId();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setBookingId((BigDecimal)value);
            }
        }
        ,
        BookingNumber {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getBookingNumber();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setBookingNumber((String)value);
            }
        }
        ,
        SaleLeaseNumber {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getSaleLeaseNumber();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setSaleLeaseNumber((String)value);
            }
        }
        ,
        CustomerTrxId {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getCustomerTrxId();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setCustomerTrxId((BigDecimal)value);
            }
        }
        ,
        CustomerTrxNumber {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getCustomerTrxNumber();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setCustomerTrxNumber((String)value);
            }
        }
        ,
        InvoicingRule {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getInvoicingRule();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setInvoicingRule((String)value);
            }
        }
        ,
        PaymentTerms {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getPaymentTerms();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setPaymentTerms((BigDecimal)value);
            }
        }
        ,
        GlDate {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getGlDate();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setGlDate((Date)value);
            }
        }
        ,
        AcntRule {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getAcntRule();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setAcntRule((String)value);
            }
        }
        ,
        RuleStartDate {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getRuleStartDate();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setRuleStartDate((Date)value);
            }
        }
        ,
        RuleEndDate {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getRuleEndDate();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setRuleEndDate((Date)value);
            }
        }
        ,
        InterfaceErrorMsg {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getInterfaceErrorMsg();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setInterfaceErrorMsg((Clob)value);
            }
        }
        ,
        AttributeCategory {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getAttributeCategory();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setAttributeCategory((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getAttribute1();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getAttribute2();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getAttribute3();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getAttribute4();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getAttribute5();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getAttribute6();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getAttribute7();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getAttribute8();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getAttribute9();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getAttribute10();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        ObjectVersion {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getObjectVersion();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setObjectVersion((BigDecimal)value);
            }
        }
        ,
        CreatedBy {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreationDate {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getCreationDate();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        XxplInvoiceLines {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getXxplInvoiceLines();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        XxplInvoiceLineVO {
            public Object get(XxplInvoiceHeaderImpl obj) {
                return obj.getXxplInvoiceLineVO();
            }

            public void put(XxplInvoiceHeaderImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(XxplInvoiceHeaderImpl object);

        public abstract void put(XxplInvoiceHeaderImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int INVOICEID = AttributesEnum.InvoiceId.index();
    public static final int INVOICENUMBER = AttributesEnum.InvoiceNumber.index();
    public static final int INVOICEDATE = AttributesEnum.InvoiceDate.index();
    public static final int FUNCID = AttributesEnum.FuncId.index();
    public static final int INVOICECLASS = AttributesEnum.InvoiceClass.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int TRXSOURCE = AttributesEnum.TrxSource.index();
    public static final int TRXTYPE = AttributesEnum.TrxType.index();
    public static final int CURRENCYCODE = AttributesEnum.CurrencyCode.index();
    public static final int EXCHANGERATE = AttributesEnum.ExchangeRate.index();
    public static final int CUSTID = AttributesEnum.CustId.index();
    public static final int CUSTSITEID = AttributesEnum.CustSiteId.index();
    public static final int DUEDATE = AttributesEnum.DueDate.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int INTERFACESTATUS = AttributesEnum.InterfaceStatus.index();
    public static final int OFFERID = AttributesEnum.OfferId.index();
    public static final int OFFERNUMBER = AttributesEnum.OfferNumber.index();
    public static final int BOOKINGID = AttributesEnum.BookingId.index();
    public static final int BOOKINGNUMBER = AttributesEnum.BookingNumber.index();
    public static final int SALELEASENUMBER = AttributesEnum.SaleLeaseNumber.index();
    public static final int CUSTOMERTRXID = AttributesEnum.CustomerTrxId.index();
    public static final int CUSTOMERTRXNUMBER = AttributesEnum.CustomerTrxNumber.index();
    public static final int INVOICINGRULE = AttributesEnum.InvoicingRule.index();
    public static final int PAYMENTTERMS = AttributesEnum.PaymentTerms.index();
    public static final int GLDATE = AttributesEnum.GlDate.index();
    public static final int ACNTRULE = AttributesEnum.AcntRule.index();
    public static final int RULESTARTDATE = AttributesEnum.RuleStartDate.index();
    public static final int RULEENDDATE = AttributesEnum.RuleEndDate.index();
    public static final int INTERFACEERRORMSG = AttributesEnum.InterfaceErrorMsg.index();
    public static final int ATTRIBUTECATEGORY = AttributesEnum.AttributeCategory.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int OBJECTVERSION = AttributesEnum.ObjectVersion.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int XXPLINVOICELINES = AttributesEnum.XxplInvoiceLines.index();
    public static final int XXPLINVOICELINEVO = AttributesEnum.XxplInvoiceLineVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxplInvoiceHeaderImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("custom.lease.model.Entity.XxplInvoiceHeader");
    }

    /**
     * Gets the attribute value for InvoiceId, using the alias name InvoiceId.
     * @return the InvoiceId
     */
    public Number getInvoiceId() {
        return (Number)getAttributeInternal(INVOICEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvoiceId.
     * @param value value to set the InvoiceId
     */
    public void setInvoiceId(Number value) {
        setAttributeInternal(INVOICEID, value);
    }

    /**
     * Gets the attribute value for InvoiceNumber, using the alias name InvoiceNumber.
     * @return the InvoiceNumber
     */
    public String getInvoiceNumber() {
        return (String)getAttributeInternal(INVOICENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvoiceNumber.
     * @param value value to set the InvoiceNumber
     */
    public void setInvoiceNumber(String value) {
        setAttributeInternal(INVOICENUMBER, value);
    }

    /**
     * Gets the attribute value for InvoiceDate, using the alias name InvoiceDate.
     * @return the InvoiceDate
     */
    public Date getInvoiceDate() {
        return (Date)getAttributeInternal(INVOICEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvoiceDate.
     * @param value value to set the InvoiceDate
     */
    public void setInvoiceDate(Date value) {
        setAttributeInternal(INVOICEDATE, value);
    }

    /**
     * Gets the attribute value for FuncId, using the alias name FuncId.
     * @return the FuncId
     */
    public BigDecimal getFuncId() {
        return (BigDecimal)getAttributeInternal(FUNCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FuncId.
     * @param value value to set the FuncId
     */
    public void setFuncId(BigDecimal value) {
        setAttributeInternal(FUNCID, value);
    }

    /**
     * Gets the attribute value for InvoiceClass, using the alias name InvoiceClass.
     * @return the InvoiceClass
     */
    public String getInvoiceClass() {
        return (String)getAttributeInternal(INVOICECLASS);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvoiceClass.
     * @param value value to set the InvoiceClass
     */
    public void setInvoiceClass(String value) {
        setAttributeInternal(INVOICECLASS, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for TrxSource, using the alias name TrxSource.
     * @return the TrxSource
     */
    public String getTrxSource() {
        return (String)getAttributeInternal(TRXSOURCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TrxSource.
     * @param value value to set the TrxSource
     */
    public void setTrxSource(String value) {
        setAttributeInternal(TRXSOURCE, value);
    }

    /**
     * Gets the attribute value for TrxType, using the alias name TrxType.
     * @return the TrxType
     */
    public String getTrxType() {
        return (String)getAttributeInternal(TRXTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TrxType.
     * @param value value to set the TrxType
     */
    public void setTrxType(String value) {
        setAttributeInternal(TRXTYPE, value);
    }

    /**
     * Gets the attribute value for CurrencyCode, using the alias name CurrencyCode.
     * @return the CurrencyCode
     */
    public String getCurrencyCode() {
        return (String)getAttributeInternal(CURRENCYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurrencyCode.
     * @param value value to set the CurrencyCode
     */
    public void setCurrencyCode(String value) {
        setAttributeInternal(CURRENCYCODE, value);
    }

    /**
     * Gets the attribute value for ExchangeRate, using the alias name ExchangeRate.
     * @return the ExchangeRate
     */
    public BigDecimal getExchangeRate() {
        return (BigDecimal)getAttributeInternal(EXCHANGERATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExchangeRate.
     * @param value value to set the ExchangeRate
     */
    public void setExchangeRate(BigDecimal value) {
        setAttributeInternal(EXCHANGERATE, value);
    }

    /**
     * Gets the attribute value for CustId, using the alias name CustId.
     * @return the CustId
     */
    public BigDecimal getCustId() {
        return (BigDecimal)getAttributeInternal(CUSTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustId.
     * @param value value to set the CustId
     */
    public void setCustId(BigDecimal value) {
        setAttributeInternal(CUSTID, value);
    }

    /**
     * Gets the attribute value for CustSiteId, using the alias name CustSiteId.
     * @return the CustSiteId
     */
    public BigDecimal getCustSiteId() {
        return (BigDecimal)getAttributeInternal(CUSTSITEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustSiteId.
     * @param value value to set the CustSiteId
     */
    public void setCustSiteId(BigDecimal value) {
        setAttributeInternal(CUSTSITEID, value);
    }

    /**
     * Gets the attribute value for DueDate, using the alias name DueDate.
     * @return the DueDate
     */
    public Date getDueDate() {
        return (Date)getAttributeInternal(DUEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DueDate.
     * @param value value to set the DueDate
     */
    public void setDueDate(Date value) {
        setAttributeInternal(DUEDATE, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the Status
     */
    public String getStatus() {
        return (String)getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for InterfaceStatus, using the alias name InterfaceStatus.
     * @return the InterfaceStatus
     */
    public String getInterfaceStatus() {
        return (String)getAttributeInternal(INTERFACESTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for InterfaceStatus.
     * @param value value to set the InterfaceStatus
     */
    public void setInterfaceStatus(String value) {
        setAttributeInternal(INTERFACESTATUS, value);
    }

    /**
     * Gets the attribute value for OfferId, using the alias name OfferId.
     * @return the OfferId
     */
    public BigDecimal getOfferId() {
        return (BigDecimal)getAttributeInternal(OFFERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OfferId.
     * @param value value to set the OfferId
     */
    public void setOfferId(BigDecimal value) {
        setAttributeInternal(OFFERID, value);
    }

    /**
     * Gets the attribute value for OfferNumber, using the alias name OfferNumber.
     * @return the OfferNumber
     */
    public String getOfferNumber() {
        return (String)getAttributeInternal(OFFERNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for OfferNumber.
     * @param value value to set the OfferNumber
     */
    public void setOfferNumber(String value) {
        setAttributeInternal(OFFERNUMBER, value);
    }

    /**
     * Gets the attribute value for BookingId, using the alias name BookingId.
     * @return the BookingId
     */
    public BigDecimal getBookingId() {
        return (BigDecimal)getAttributeInternal(BOOKINGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BookingId.
     * @param value value to set the BookingId
     */
    public void setBookingId(BigDecimal value) {
        setAttributeInternal(BOOKINGID, value);
    }

    /**
     * Gets the attribute value for BookingNumber, using the alias name BookingNumber.
     * @return the BookingNumber
     */
    public String getBookingNumber() {
        return (String)getAttributeInternal(BOOKINGNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for BookingNumber.
     * @param value value to set the BookingNumber
     */
    public void setBookingNumber(String value) {
        setAttributeInternal(BOOKINGNUMBER, value);
    }

    /**
     * Gets the attribute value for SaleLeaseNumber, using the alias name SaleLeaseNumber.
     * @return the SaleLeaseNumber
     */
    public String getSaleLeaseNumber() {
        return (String)getAttributeInternal(SALELEASENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for SaleLeaseNumber.
     * @param value value to set the SaleLeaseNumber
     */
    public void setSaleLeaseNumber(String value) {
        setAttributeInternal(SALELEASENUMBER, value);
    }

    /**
     * Gets the attribute value for CustomerTrxId, using the alias name CustomerTrxId.
     * @return the CustomerTrxId
     */
    public BigDecimal getCustomerTrxId() {
        return (BigDecimal)getAttributeInternal(CUSTOMERTRXID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerTrxId.
     * @param value value to set the CustomerTrxId
     */
    public void setCustomerTrxId(BigDecimal value) {
        setAttributeInternal(CUSTOMERTRXID, value);
    }

    /**
     * Gets the attribute value for CustomerTrxNumber, using the alias name CustomerTrxNumber.
     * @return the CustomerTrxNumber
     */
    public String getCustomerTrxNumber() {
        return (String)getAttributeInternal(CUSTOMERTRXNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerTrxNumber.
     * @param value value to set the CustomerTrxNumber
     */
    public void setCustomerTrxNumber(String value) {
        setAttributeInternal(CUSTOMERTRXNUMBER, value);
    }

    /**
     * Gets the attribute value for InvoicingRule, using the alias name InvoicingRule.
     * @return the InvoicingRule
     */
    public String getInvoicingRule() {
        return (String)getAttributeInternal(INVOICINGRULE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvoicingRule.
     * @param value value to set the InvoicingRule
     */
    public void setInvoicingRule(String value) {
        setAttributeInternal(INVOICINGRULE, value);
    }

    /**
     * Gets the attribute value for PaymentTerms, using the alias name PaymentTerms.
     * @return the PaymentTerms
     */
    public BigDecimal getPaymentTerms() {
        return (BigDecimal)getAttributeInternal(PAYMENTTERMS);
    }

    /**
     * Sets <code>value</code> as the attribute value for PaymentTerms.
     * @param value value to set the PaymentTerms
     */
    public void setPaymentTerms(BigDecimal value) {
        setAttributeInternal(PAYMENTTERMS, value);
    }

    /**
     * Gets the attribute value for GlDate, using the alias name GlDate.
     * @return the GlDate
     */
    public Date getGlDate() {
        return (Date)getAttributeInternal(GLDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for GlDate.
     * @param value value to set the GlDate
     */
    public void setGlDate(Date value) {
        setAttributeInternal(GLDATE, value);
    }

    /**
     * Gets the attribute value for AcntRule, using the alias name AcntRule.
     * @return the AcntRule
     */
    public String getAcntRule() {
        return (String)getAttributeInternal(ACNTRULE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AcntRule.
     * @param value value to set the AcntRule
     */
    public void setAcntRule(String value) {
        setAttributeInternal(ACNTRULE, value);
    }

    /**
     * Gets the attribute value for RuleStartDate, using the alias name RuleStartDate.
     * @return the RuleStartDate
     */
    public Date getRuleStartDate() {
        return (Date)getAttributeInternal(RULESTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RuleStartDate.
     * @param value value to set the RuleStartDate
     */
    public void setRuleStartDate(Date value) {
        setAttributeInternal(RULESTARTDATE, value);
    }

    /**
     * Gets the attribute value for RuleEndDate, using the alias name RuleEndDate.
     * @return the RuleEndDate
     */
    public Date getRuleEndDate() {
        return (Date)getAttributeInternal(RULEENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RuleEndDate.
     * @param value value to set the RuleEndDate
     */
    public void setRuleEndDate(Date value) {
        setAttributeInternal(RULEENDDATE, value);
    }

    /**
     * Gets the attribute value for InterfaceErrorMsg, using the alias name InterfaceErrorMsg.
     * @return the InterfaceErrorMsg
     */
    public Clob getInterfaceErrorMsg() {
        return (Clob)getAttributeInternal(INTERFACEERRORMSG);
    }

    /**
     * Sets <code>value</code> as the attribute value for InterfaceErrorMsg.
     * @param value value to set the InterfaceErrorMsg
     */
    public void setInterfaceErrorMsg(Clob value) {
        setAttributeInternal(INTERFACEERRORMSG, value);
    }

    /**
     * Gets the attribute value for AttributeCategory, using the alias name AttributeCategory.
     * @return the AttributeCategory
     */
    public String getAttributeCategory() {
        return (String)getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeCategory.
     * @param value value to set the AttributeCategory
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ObjectVersion, using the alias name ObjectVersion.
     * @return the ObjectVersion
     */
    public BigDecimal getObjectVersion() {
        return (BigDecimal)getAttributeInternal(OBJECTVERSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for ObjectVersion.
     * @param value value to set the ObjectVersion
     */
    public void setObjectVersion(BigDecimal value) {
        setAttributeInternal(OBJECTVERSION, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }


    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp)getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }


    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp)getAttributeInternal(LASTUPDATEDATE);
    }


    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public String getLastUpdateLogin() {
        return (String)getAttributeInternal(LASTUPDATELOGIN);
    }


    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getXxplInvoiceLines() {
        return (RowIterator)getAttributeInternal(XXPLINVOICELINES);
    }


    /**
     * Uses the link XxplInvoiceVL to return rows of XxplInvoiceLineVO
     */
    public RowIterator getXxplInvoiceLineVO() {
        return (RowIterator)getAttributeInternal(XXPLINVOICELINEVO);
    }


    /**
     * @param invoiceId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number invoiceId) {
        return new Key(new Object[]{invoiceId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        SequenceImpl seq = new SequenceImpl("INVOICE_ID_S", this.getDBTransaction());
       this.setInvoiceId(seq.getSequenceNumber());
        super.create(attributeList);
    }
}
